### ISSUE TITLE
aspnet_viewstate module missing response-body error handling

### ISSUE THREAD

**Issue by liquidsec** [blacklanternsecurity/bbot#100]
aspnet_viewstate module is occasionally throwing an error when HTTPX does not include a response-body, as shown below.

```
[ERRR] bbot.scanner.manager: Error in aspnet_viewstate.handle_event(): 'response-body'
[DBUG] bbot.scanner.manager: Traceback (most recent call last):
  File "/home/xxxxxxxxxx/.local/lib/python3.9/site-packages/bbot/scanner/manager.py", line 266, in catch
    ret = callback(*args, **kwargs)
  File "/home/xxxxxxxxxxx/.local/lib/python3.9/site-packages/bbot/modules/aspnet_viewstate.py", line 48, in handle_event
    generator_match = self.generator_regex.search(event.data["response-body"])
KeyError: 'response-body'
```

This is not leading to false negatives.

Need to improve error handling.

**Comment by liquidsec** [comment]
fixed in https://github.com/blacklanternsecurity/bbot/pull/108
