### ISSUE TITLE
Bug in Bypass403

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#1057]
```
2024-02-03 13:47:02,614 [ERROR] bbot.scanner scanner.py:1056 Error in bypass403.handle_event(URL("https://epc-support.tesla.com/", module=httpx, tags={'cdn-akamai', 'dir', 'status-403', 'in-scope', 'ip-23-216-136-64', 'mutation-1', 'http-title-access-denied'})): /root/bbot/bbot/core/helpers/diff.py:98:compare_headers(): 'HttpCompare' object has no attribute 'baseline_ignore_headers'
2024-02-03 13:47:02,615 [TRACE] bbot.scanner logger.py:83 Traceback (most recent call last):
  File "/root/bbot/bbot/scanner/scanner.py", line 1039, in _acatch
    yield
  File "/root/bbot/bbot/modules/base.py", line 599, in _worker
    await handle_event_task
  File "/root/bbot/bbot/modules/bypass403.py", line 131, in handle_event
    results = await self.do_checks(compare_helper, event, collapse_threshold)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/bbot/bbot/modules/bypass403.py", line 94, in do_checks
    match, reasons, reflection, subject_response = await compare_helper.compare(
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/bbot/bbot/core/helpers/diff.py", line 183, in compare
    different_headers = self.compare_headers(self.baseline.headers, subject_response.headers)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/bbot/bbot/core/helpers/diff.py", line 98, in compare_headers
    if header.lower() in self.baseline_ignore_headers:
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'HttpCompare' object has no attribute 'baseline_ignore_headers'
```

**Comment by liquidsec** [comment]
Looks like it's an async race condition. Adding in debugging print statements or small sleep() completely prevents it. Looking into a fix.

**Comment by liquidsec** [comment]
Async Calls to the async _baseline() were modifying the the attribute _baselined, which exists in the (non-async) __init__ within the HttpCompare object. 

Since the self._baselined attribute was set right at the beginning of _baseline, subsequent calls to compare were seeing that the baseline was complete when it was actually in progress.

Moving the _basedlined = True to the bottom of the function seems to fix the problem.

**Comment by liquidsec** [comment]
fixed in https://github.com/blacklanternsecurity/bbot/pull/1059
