### ISSUE TITLE
Gowitness decode error

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#1071]
```
2024-02-06 18:37:44,260 [ERROR] bbot.scanner scanner.py:1059 Error in gowitness.handle_batch(): /root/bbot_dev/bbot/modules/gowitness.py:205:new_screenshots(): Could not decode to UTF-8 column 'title' with text '403 - Interdit�: acc�s refus�.'
2024-02-06 18:37:44,261 [TRACE] bbot.scanner scanner.py:1060 Traceback (most recent call last):
  File "/root/bbot_dev/bbot/scanner/scanner.py", line 1042, in _acatch
    yield
  File "/root/bbot_dev/bbot/modules/base.py", line 365, in _handle_batch
    await handle_batch_task
  File "/root/bbot_dev/bbot/modules/gowitness.py", line 142, in handle_batch
    for filename, screenshot in self.new_screenshots.items():
  File "/root/bbot_dev/bbot/modules/gowitness.py", line 205, in new_screenshots
    for row in res:
sqlite3.OperationalError: Could not decode to UTF-8 column 'title' with text '403 - Interdit�: acc�s refus�.'
```

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/1073. See https://stackoverflow.com/questions/22751363/sqlite3-operationalerror-could-not-decode-to-utf-8-column.
