### ISSUE TITLE
Ansible debug is displayed even when debug is not enabled

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#1078]

**Comment by TheTechromancer** [comment]
This causes problems when json output is enabled and bbot is piped to `jq`. Because ansible prints to stdout, jq fails to decode the output as JSON and dies, which causes the scan to fail spectacularly:

```
jq: parse error: Invalid numeric literal at line 1, column 2
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/bls/Downloads/code/bbot/bbot/cli.py", line 255, in main
    asyncio.run(_main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/bls/Downloads/code/bbot/bbot/cli.py", line 165, in _main
    await scan._prep()
  File "/home/bls/Downloads/code/bbot/bbot/scanner/scanner.py", line 241, in _prep
    await self.load_modules()
  File "/home/bls/Downloads/code/bbot/bbot/scanner/scanner.py", line 469, in load_modules
    succeeded, failed = await self.helpers.depsinstaller.install(*self.preset.modules)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bls/Downloads/code/bbot/bbot/core/helpers/depsinstaller/installer.py", line 99, in install
    success = await self.install_module(m)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bls/Downloads/code/bbot/bbot/core/helpers/depsinstaller/installer.py", line 133, in install_module
    success &= self.tasks(module, ansible_tasks)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bls/Downloads/code/bbot/bbot/core/helpers/depsinstaller/installer.py", line 242, in tasks
    success, err = self.ansible_run(tasks=tasks)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bls/Downloads/code/bbot/bbot/core/helpers/depsinstaller/installer.py", line 276, in ansible_run
    res = run(
          ^^^^
  File "/home/bls/.cache/pypoetry/virtualenvs/bbot-yxGMlPK5-py3.12/lib/python3.12/site-packages/ansible_runner/interface.py", line 210, in run
    r.run()
  File "/home/bls/.cache/pypoetry/virtualenvs/bbot-yxGMlPK5-py3.12/lib/python3.12/site-packages/ansible_runner/runner.py", line 318, in run
    result_id = child.expect(password_patterns, timeout=self.config.pexpect_timeout, searchwindowsize=100)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bls/.cache/pypoetry/virtualenvs/bbot-yxGMlPK5-py3.12/lib/python3.12/site-packages/pexpect/spawnbase.py", line 354, in expect
    return self.expect_list(compiled_pattern_list,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bls/.cache/pypoetry/virtualenvs/bbot-yxGMlPK5-py3.12/lib/python3.12/site-packages/pexpect/spawnbase.py", line 383, in expect_list
    return exp.expect_loop(timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bls/.cache/pypoetry/virtualenvs/bbot-yxGMlPK5-py3.12/lib/python3.12/site-packages/pexpect/expect.py", line 169, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bls/.cache/pypoetry/virtualenvs/bbot-yxGMlPK5-py3.12/lib/python3.12/site-packages/pexpect/pty_spawn.py", line 501, in read_nonblocking
    return super(spawn, self).read_nonblocking(size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bls/.cache/pypoetry/virtualenvs/bbot-yxGMlPK5-py3.12/lib/python3.12/site-packages/pexpect/spawnbase.py", line 192, in read_nonblocking
    self._log(s, 'read')
  File "/home/bls/.cache/pypoetry/virtualenvs/bbot-yxGMlPK5-py3.12/lib/python3.12/site-packages/pexpect/spawnbase.py", line 133, in _log
    second_log.write(s)
  File "/home/bls/.cache/pypoetry/virtualenvs/bbot-yxGMlPK5-py3.12/lib/python3.12/site-packages/ansible_runner/utils/__init__.py", line 356, in write
    sys.stdout.write(
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/1483.
