### ISSUE TITLE
aioconsole causes stdout crash

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#1079]
Sometimes when pressing enter during a scan (especially when a lot of stuff is being printed to the console), aioconsole throws an error. After this point, stdout no longer works.

```
Traceback (most recent call last):
  File "/root/bbot/bbot/cli.py", line 329, in akeyboard_listen
    keyboard_input = await ainput()
                     ^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/bbot-aKeTQkGo-py3.11/lib/python3.11/site-packages/aioconsole/stream.py", line 284, in ainput
    raise EOFError
EOFError
```

**Comment by TheTechromancer** [comment]
The crash in aioconsole happens because `aioconsole.ainput()` puts both stdin and stdout into non-blocking mode. When our logger tries to write to it, it fails and everything crashes spectacularly.

There is already an [upstream issue](https://github.com/vxgmichel/aioconsole/issues/99) for this, which reproduces the error using the following code:

```python
import asyncio
from aioconsole import ainput


async def main():
    await ainput("ainput: ")
    input("input: ")

asyncio.run(main())
```

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/1051.
