### ISSUE TITLE
SOCKS Malformed Reply

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#1096]
Thanks to @amiremami for discovering.

```
2024-02-16 09:50:50,383 [TRACE] bbot.core.helpers.web web.py:624 Unhandled exception with request to URL: http://sts.windows.net: Malformed reply
2024-02-16 09:50:50,384 [TRACE] bbot.core.helpers.web web.py:625 Traceback (most recent call last):
  File "/root/.local/pipx/venvs/bbot/lib/python3.10/site-packages/bbot/core/helpers/web.py", line 593, in _acatch
    yield
  File "/root/.local/pipx/venvs/bbot/lib/python3.10/site-packages/bbot/core/helpers/web.py", line 228, in request
    response = await client.request(*args, **kwargs)
  File "/root/.local/pipx/venvs/bbot/lib/python3.10/site-packages/bbot/core/helpers/web.py", line 86, in request
    return await super().request(*args, **kwargs)
  File "/root/.local/pipx/venvs/bbot/lib/python3.10/site-packages/httpx/_client.py", line 1559, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/root/.local/pipx/venvs/bbot/lib/python3.10/site-packages/httpx/_client.py", line 1646, in send
    response = await self._send_handling_auth(
  File "/root/.local/pipx/venvs/bbot/lib/python3.10/site-packages/httpx/_client.py", line 1674, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/root/.local/pipx/venvs/bbot/lib/python3.10/site-packages/httpx/_client.py", line 1711, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/root/.local/pipx/venvs/bbot/lib/python3.10/site-packages/httpx/_client.py", line 1748, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/root/.local/pipx/venvs/bbot/lib/python3.10/site-packages/httpx/_transports/default.py", line 371, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/root/.local/pipx/venvs/bbot/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 268, in handle_async_request
    raise exc
  File "/root/.local/pipx/venvs/bbot/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 251, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/root/.local/pipx/venvs/bbot/lib/python3.10/site-packages/httpcore/_async/socks_proxy.py", line 296, in handle_async_request
    raise exc
  File "/root/.local/pipx/venvs/bbot/lib/python3.10/site-packages/httpcore/_async/socks_proxy.py", line 245, in handle_async_request
    await _init_socks5_connection(**kwargs)
  File "/root/.local/pipx/venvs/bbot/lib/python3.10/site-packages/httpcore/_async/socks_proxy.py", line 97, in _init_socks5_connection
    response = conn.receive_data(incoming_bytes)
  File "/root/.local/pipx/venvs/bbot/lib/python3.10/site-packages/socksio/socks5.py", line 382, in receive_data
    reply = SOCKS5Reply.loads(data)
  File "/root/.local/pipx/venvs/bbot/lib/python3.10/site-packages/socksio/socks5.py", line 254, in loads
    raise ProtocolError("Malformed reply")
socksio.exceptions.ProtocolError: Malformed reply
```

**Comment by TheTechromancer** [comment]
Should be fixed in https://github.com/blacklanternsecurity/bbot/pull/1098.
