### ISSUE TITLE
httpx issue causes module setups to fail

### ISSUE THREAD

**Issue by batgoose** [blacklanternsecurity/bbot#1099]
**Describe the bug**
"Setup hard-failed for 2 modules (generic_ssrf,host_header)" when starting a scan using those modules

**Expected behavior**
What was supposed to happen?
start scan

**BBOT Command**
bbot scan with generic_ssfc and/or host_header

**OS, BBOT Version**
ubuntu, 1.1.5

**Traceback**
[WARN] generic_ssrf: Setting error state
[TRCE] generic_ssrf: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/bbot/modules/base.py", line 542, in _setup
    result = await setup_task
  File "/usr/local/lib/python3.10/site-packages/bbot/modules/generic_ssrf.py", line 169, in setup
    self.interactsh_domain = await self.interactsh_instance.register(callback=self.interactsh_callback)
  File "/usr/local/lib/python3.10/site-packages/bbot/core/helpers/interactsh.py", line 140, in register
    r = await self.parent_helper.request(
  File "/usr/local/lib/python3.10/site-packages/bbot/core/helpers/web.py", line 228, in request
    response = await client.request(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/bbot/core/helpers/web.py", line 86, in request
    return await super().request(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1546, in request
    request = self.build_request(
  File "/usr/local/lib/python3.10/site-packages/bbot/core/helpers/web.py", line 89, in build_request
    request = super().build_request(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 348, in build_request
    headers = self._merge_headers(headers)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 415, in _merge_headers
    merged_headers.update(headers)
  File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 199, in update
    headers = Headers(headers)
  File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 70, in __init__
    self._list = [
  File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 74, in <listcomp>
    normalize_header_value(v, encoding),
  File "/usr/local/lib/python3.10/site-packages/httpx/_utils.py", line 53, in normalize_header_value
    return value.encode(encoding or "ascii")
AttributeError: 'NoneType' object has no attribute 'encode'

[DBUG] generic_ssrf: Emptying event_queue
[TRCE] generic_ssrf: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/bbot/modules/base.py", line 542, in _setup
    result = await setup_task
  File "/usr/local/lib/python3.10/site-packages/bbot/modules/generic_ssrf.py", line 169, in setup
    self.interactsh_domain = await self.interactsh_instance.register(callback=self.interactsh_callback)
  File "/usr/local/lib/python3.10/site-packages/bbot/core/helpers/interactsh.py", line 140, in register
    r = await self.parent_helper.request(
  File "/usr/local/lib/python3.10/site-packages/bbot/core/helpers/web.py", line 228, in request
    response = await client.request(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/bbot/core/helpers/web.py", line 86, in request
    return await super().request(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1546, in request
    request = self.build_request(
  File "/usr/local/lib/python3.10/site-packages/bbot/core/helpers/web.py", line 89, in build_request
    request = super().build_request(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 348, in build_request
    headers = self._merge_headers(headers)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 415, in _merge_headers
    merged_headers.update(headers)
  File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 199, in update
    headers = Headers(headers)
  File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 70, in __init__
    self._list = [
  File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 74, in <listcomp>
    normalize_header_value(v, encoding),
  File "/usr/local/lib/python3.10/site-packages/httpx/_utils.py", line 53, in normalize_header_value
    return value.encode(encoding or "ascii")
AttributeError: 'NoneType' object has no attribute 'encode'

**Comment by TheTechromancer** [comment]
I'm having trouble reproducing this one. Can you post your config?

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/1100.
