### ISSUE TITLE
Error in dnscommonsrv

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#113]
`[ERRR] bbot.scanner.manager: Error in ScanManager._emit_event(): 6841513254754510330`

When running:
```bash
bbot -f subdomain-enum -m httpx -t evilcorp.com -n evilcorp -o . -c modules.massdns.max_resolver=5000
```

Update:
```
2022-10-06 04:56:17,807 [DEBUG] bbot.modules.dnscommonsrv base.py:543 Traceback (most recent call last):
  File "/root/.local/pipx/venvs/bbot/lib/python3.9/site-packages/bbot/modules/base.py", line 425, in _event_postcheck
    if not self.filter_event(event):
  File "/root/.local/pipx/venvs/bbot/lib/python3.9/site-packages/bbot/modules/dnscommonsrv.py", line 100, in filter_event
    is_wildcard, _ = self.helpers.is_wildcard(event.host)
  File "/root/.local/pipx/venvs/bbot/lib/python3.9/site-packages/bbot/core/helpers/dns.py", line 530, in is_wildcard
    query_ips = self.resolve(query, type=("A", "AAAA"), retries=retries, cache_result=True)
  File "/root/.local/pipx/venvs/bbot/lib/python3.9/site-packages/bbot/core/helpers/dns.py", line 86, in resolve
    raw_results, errors = self.resolve_raw(query, **kwargs)
  File "/root/.local/pipx/venvs/bbot/lib/python3.9/site-packages/bbot/core/helpers/dns.py", line 122, in resolve_raw
    r, e = self._resolve_hostname(query, rdtype=t, **kwargs)
  File "/root/.local/pipx/venvs/bbot/lib/python3.9/site-packages/bbot/core/helpers/dns.py", line 150, in _resolve_hostname
    results = self._dns_cache[dns_cache_hash]
  File "/root/.local/pipx/venvs/bbot/lib/python3.9/site-packages/bbot/core/helpers/cache.py", line 128, in __getitem__
    return self.get(item)
  File "/root/.local/pipx/venvs/bbot/lib/python3.9/site-packages/bbot/core/helpers/cache.py", line 76, in get
    return self._cache[name_hash]
KeyError: 8714145451267874800
```

**Comment by TheTechromancer** [comment]
I think this is fixed
