### ISSUE TITLE
Error with Badsecrets with werkzeug dependency 

### ISSUE THREAD

**Issue by aconite33** [blacklanternsecurity/bbot#1135]
**Describe the bug**
Running a scan with badsecrets module

**Expected behavior**
Successful scan to start

**BBOT Command**
Example: `bbot -m badsecrets -t evilcorp.com`

**OS, BBOT Installation Method + Version**
Example: `OS: Arch Linux, Installation method: pipenv/poetry, BBOT version: Latest Dev`

**Logs**
Stacktrace:

```
[ERRR] Encountered unknown error: Traceback (most recent call last):
  File "/root/bbot_dev/bbot/cli.py", line 301, in _main
    await scanner._prep()
  File "/root/bbot_dev/bbot/scanner/scanner.py", line 295, in _prep
    await self.load_modules()
  File "/root/bbot_dev/bbot/scanner/scanner.py", line 523, in load_modules
    loaded_modules, failed = self._load_modules(modules)
  File "/root/bbot_dev/bbot/scanner/scanner.py", line 1017, in _load_modules
    for module_name, module_class in module_loader.load_modules(modules).items():
  File "/root/bbot_dev/bbot/core/helpers/modules.py", line 252, in load_modules
    module = self.load_module(module_name)
  File "/root/bbot_dev/bbot/core/helpers/modules.py", line 276, in load_module
    module_variables = importlib.import_module(import_path, "bbot")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/bbot_dev/bbot/modules/badsecrets.py", line 5, in <module>
    from badsecrets.base import carve_all_modules
  File "/root/.local/share/virtualenvs/bbot_dev-KnMjRjwb/lib/python3.10/site-packages/badsecrets/__init__.py", line 12, in <module>
    modules = importlib.import_module(f"badsecrets.modules.{file.stem}", "badsecrets")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/root/.local/share/virtualenvs/bbot_dev-KnMjRjwb/lib/python3.10/site-packages/badsecrets/modules/flask_signedcookies.py", line 4, in <module>
    from flask_unsign import verify as flaskVerify
  File "/root/.local/share/virtualenvs/bbot_dev-KnMjRjwb/lib/python3.10/site-packages/flask_unsign/__init__.py", line 26, in <module>
    from flask_unsign.session import sign, decode, verify
  File "/root/.local/share/virtualenvs/bbot_dev-KnMjRjwb/lib/python3.10/site-packages/flask_unsign/session.py", line 9, in <module>
    from flask.json.tag import TaggedJSONSerializer
  File "/root/.local/share/virtualenvs/bbot_dev-KnMjRjwb/lib/python3.10/site-packages/flask/__init__.py", line 5, in <module>
    from .app import Flask as Flask
  File "/root/.local/share/virtualenvs/bbot_dev-KnMjRjwb/lib/python3.10/site-packages/flask/app.py", line 30, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/root/.local/share/virtualenvs/bbot_dev-KnMjRjwb/lib/python3.10/site-packages/werkzeug/urls.py)

(bbot_dev) root@ubuntu-s-2vcpu-4gb-nyc1-01:~/bbot_dev# /usr/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 5 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**Comment by liquidsec** [comment]
@aconite33 were you ever able to replicate this with any sequence of installs/upgrades?
