### ISSUE TITLE
Tabulate Error

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#1246]
This old bug came back:

```
$ bbot -t nuclei --allow-deadly
[INFO] 
[INFO] ### MODULES ###
[INFO] 
[ERRR] Encountered unknown error: Traceback (most recent call last):
  File "/home/bls/Downloads/code/bbot/bbot/cli.py", line 245, in _main
    for row in module_loader.modules_table(modules=help_modules).splitlines():
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bls/Downloads/code/bbot/bbot/core/helpers/modules.py", line 407, in modules_table
    return make_table(table, header, maxcolwidths=maxcolwidths)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bls/Downloads/code/bbot/bbot/core/helpers/misc.py", line 2018, in make_table
    return tabulate(rows, header, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bls/.cache/pypoetry/virtualenvs/bbot-yxGMlPK5-py3.11/lib/python3.11/site-packages/tabulate.py", line 1623, in tabulate
    num_cols = len(list_of_lists[0])
                   ~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/1247.
