### ISSUE TITLE
Nuclei setup is failing in tests

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#1248]
```
TRACE    bbot.modules.nuclei:logger.py:83 Traceback (most recent call last):
  File "/home/bls/Downloads/code/bbot/bbot/modules/base.py", line 553, in _setup
    result = await setup_task
             ^^^^^^^^^^^^^^^^
  File "/home/bls/Downloads/code/bbot/bbot/modules/deadly/nuclei.py", line 125, in setup
    self.nucleibudget = NucleiBudget(self)
                        ^^^^^^^^^^^^^^^^^^
  File "/home/bls/Downloads/code/bbot/bbot/modules/deadly/nuclei.py", line 313, in __init__
    self.budget_paths = self.find_budget_paths(nuclei_module.budget)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bls/Downloads/code/bbot/bbot/modules/deadly/nuclei.py", line 325, in find_budget_paths
    for path in paths:
TypeError: 'NoneType' object is not iterable

WARNING  bbot.scanner:scanner.py:920 Setup hard-failed for nuclei: 'NoneType' object is not iterable
```

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/1249.
