### ISSUE TITLE
Filedownload error

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#1251]
```
2024-04-10 11:31:26,252 [ERROR] bbot.scanner scanner.py:1059 Error in filedownload.handle_event(HTTP_RESPONSE("{'url': 'http://fleet-streaming-api.prd.vn.cloud.tesla.com:443/', 'timestamp': '...", module=httpx, tags={'cloud-amazon', 'ip-100-20-225-59', 'in-scope', 'status-400', 'dir'})): /home/bls/Downloads/code/bbot/bbot/modules/filedownload.py:123:handle_event(): 'header'
2024-04-10 11:31:26,252 [TRACE] bbot.scanner logger.py:83 Traceback (most recent call last):
  File "/home/bls/Downloads/code/bbot/bbot/scanner/scanner.py", line 1042, in _acatch
    yield
  File "/home/bls/Downloads/code/bbot/bbot/modules/base.py", line 629, in _worker
    await handle_event_task
  File "/home/bls/Downloads/code/bbot/bbot/modules/filedownload.py", line 123, in handle_event
    content_type = event.data["header"].get("content_type", "")
                   ~~~~~~~~~~^^^^^^^^^^
KeyError: 'header'
```

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/1253.
