### ISSUE TITLE
Error in _write_proc_line(): 'Process' object has no attribute 'args'

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#1254]
```
2024-04-10 19:56:15,863 [ERROR] bbot.scanner scanner.py:1015 Error in httpx.handle_batch(): /home/bls/Downloads/code/bbot/bbot/core/helpers/command.py:188:_write_proc_line(): 'Process' object has no attribute 'args'
2024-04-10 19:56:15,863 [TRACE] bbot.scanner logger.py:109 Traceback (most recent call last):
  File "/home/bls/Downloads/code/bbot/bbot/core/helpers/command.py", line 186, in _write_proc_line
    await proc.stdin.drain()
  File "/usr/lib/python3.11/asyncio/streams.py", line 392, in drain
    await self._protocol._drain_helper()
  File "/usr/lib/python3.11/asyncio/streams.py", line 166, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bls/Downloads/code/bbot/bbot/scanner/scanner.py", line 998, in _acatch
    yield
  File "/home/bls/Downloads/code/bbot/bbot/modules/base.py", line 397, in _handle_batch
    await self.handle_batch(*events)
  File "/home/bls/Downloads/code/bbot/bbot/modules/httpx.py", line 136, in handle_batch
    async for line in self.run_process_live(command, input=list(stdin), stderr=subprocess.DEVNULL):
  File "/home/bls/Downloads/code/bbot/bbot/modules/base.py", line 1046, in run_process_live
    async for line in self.helpers.run_live(*args, **kwargs):
  File "/home/bls/Downloads/code/bbot/bbot/core/helpers/command.py", line 121, in run_live
    await input_task
  File "/home/bls/Downloads/code/bbot/bbot/core/helpers/command.py", line 210, in _write_stdin
    await _write_proc_line(proc, chunk)
  File "/home/bls/Downloads/code/bbot/bbot/core/helpers/command.py", line 188, in _write_proc_line
    command = " ".join([str(s) for s in proc.args])
                                        ^^^^^^^^^
AttributeError: 'Process' object has no attribute 'args'
```

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/1277.
