### ISSUE TITLE
cloud-enum can not handle Punycode domains

### ISSUE THREAD

**Issue by PfiatDe** [blacklanternsecurity/bbot#1258]
**Describe the bug**
cloud-enum can not handle Punycode domains

**Expected behavior**
cloud-enum should at least not throw errors. Maybe just skip or use the punycode writing instead?

**BBOT Command**
`bbot -t xn--mbel4-jua.de -f cloud-enum`

**OS, BBOT Installation Method + Version**
`OS: Debian 12, Installation method: pipx, BBOT version: 1.1.6`
Note: You can get the bbot version with `bbot --version`

**Logs**
```
user@aproj~/.b/scans> bbot -t xn--mbel4-jua.de -f cloud-enum
[...]
[SUCC] Setup succeeded for 17/17 modules.
[SUCC] Scan ready. Press enter to execute sinister_samantha

[SUCC] Starting scan sinister_samantha
[SCAN]              	sinister_samantha (SCAN:89d4a3034daf25f97dc26a64b0be78f7c872f45a)	TARGET	(in-scope)
[INFO] Encountered domain with wildcard DNS (A): xn--mbel4-jua.de
[DNS_NAME]          	xn--mbel4-jua.de	TARGET	(a-record, a-wildcard-domain, domain, in-scope, mx-record, ns-record, resolved, soa-record, target, txt-record, wildcard-domain)
[ERRR] Error in bucket_amazon.handle_event(DNS_NAME("xn--mbel4-jua.de", module=TARGET, tags={'domain', 'soa-record', 'target', 'txt-record', 'resolved', 'a-record', 'ns-record', 'in-scope', 'a-wildcard-domain', 'mx-record', 'wildcard-domain'})): /home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/idna/core.py:298:ulabel(): Invalid A-label
[ERRR] Error in bucket_azure.handle_event(DNS_NAME("xn--mbel4-jua.de", module=TARGET, tags={'domain', 'soa-record', 'target', 'txt-record', 'resolved', 'a-record', 'ns-record', 'in-scope', 'a-wildcard-domain', 'mx-record', 'wildcard-domain'})): /home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/idna/core.py:250:check_label(): Codepoint U+00F7 at position 3 of 'mö÷belö4' not allowed
[ERRR] Error in bucket_digitalocean.handle_event(DNS_NAME("xn--mbel4-jua.de", module=TARGET, tags={'domain', 'soa-record', 'target', 'txt-record', 'resolved', 'a-record', 'ns-record', 'in-scope', 'a-wildcard-domain', 'mx-record', 'wildcard-domain'})): /home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/idna/core.py:250:check_label(): Codepoint U+00F7 at position 3 of 'mö÷belö4' not allowed
[ERRR] Task exception was never retrieved
future: <Task finished name='Task-111' coro=<bucket_template._check_bucket_exists() done, defined at /home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/bbot/modules/templates/bucket.py:93> exception=InvalidCodepoint("Codepoint U+00F7 at position 3 of 'mö÷belö4' not allowed")>
Traceback (most recent call last):
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/bbot/modules/templates/bucket.py", line 95, in _check_bucket_exists
    return await self.check_bucket_exists(bucket_name, url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/bbot/modules/templates/bucket.py", line 98, in check_bucket_exists
    response = await self.helpers.request(url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/bbot/core/helpers/web.py", line 229, in request
    response = await client.request(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/bbot/core/helpers/web.py", line 87, in request
    return await super().request(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/httpx/_client.py", line 1546, in request
    request = self.build_request(
              ^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/bbot/core/helpers/web.py", line 90, in build_request
    request = super().build_request(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/httpx/_client.py", line 359, in build_request
    return Request(
           ^^^^^^^^
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/httpx/_models.py", line 349, in __init__
    self._prepare(headers)
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/httpx/_models.py", line 385, in _prepare
    if not has_host and self.url.host:
                        ^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/httpx/_urls.py", line 189, in host
    host = idna.decode(host)
           ^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/idna/core.py", line 388, in decode
    s = ulabel(label)
        ^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/idna/core.py", line 299, in ulabel
    check_label(label)
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/idna/core.py", line 250, in check_label
    raise InvalidCodepoint('Codepoint {} at position {} of {} not allowed'.format(_unot(cp_value), pos+1, repr(label)))
idna.core.InvalidCodepoint: Codepoint U+00F7 at position 3 of 'mö÷belö4' not allowed
[ERRR] Task exception was never retrieved
future: <Task finished name='Task-112' coro=<bucket_template._check_bucket_exists() done, defined at /home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/bbot/modules/templates/bucket.py:93> exception=IDNAError('Invalid A-label')>
Traceback (most recent call last):
  File "/usr/lib/python3.11/encodings/punycode.py", line 134, in decode_generalized_number
    char = ord(extended[extpos])
               ~~~~~~~~^^^^^^^^
IndexError: string index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/encodings/punycode.py", line 207, in decode
    res = punycode_decode(input, errors)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/encodings/punycode.py", line 194, in punycode_decode
    return insertion_sort(base, extended, errors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/encodings/punycode.py", line 164, in insertion_sort
    newpos, delta = decode_generalized_number(extended, extpos,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/encodings/punycode.py", line 137, in decode_generalized_number
    raise UnicodeError("incomplete punicode string")
UnicodeError: incomplete punicode string

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/idna/core.py", line 296, in ulabel
    label = label_bytes.decode('punycode')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeError: decoding with 'punycode' codec failed (UnicodeError: incomplete punicode string)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/bbot/modules/templates/bucket.py", line 95, in _check_bucket_exists
    return await self.check_bucket_exists(bucket_name, url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/bbot/modules/bucket_azure.py", line 22, in check_bucket_exists
    response = await self.helpers.request(url, retries=0)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/bbot/core/helpers/web.py", line 229, in request
    response = await client.request(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/bbot/core/helpers/web.py", line 87, in request
    return await super().request(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/httpx/_client.py", line 1546, in request
    request = self.build_request(
              ^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/bbot/core/helpers/web.py", line 90, in build_request
    request = super().build_request(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/httpx/_client.py", line 359, in build_request
    return Request(
           ^^^^^^^^
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/httpx/_models.py", line 349, in __init__
    self._prepare(headers)
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/httpx/_models.py", line 385, in _prepare
    if not has_host and self.url.host:
                        ^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/httpx/_urls.py", line 189, in host
    host = idna.decode(host)
           ^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/idna/core.py", line 388, in decode
    s = ulabel(label)
        ^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/idna/core.py", line 298, in ulabel
    raise IDNAError('Invalid A-label')
idna.core.IDNAError: Invalid A-label
[ERRR] Task exception was never retrieved
future: <Task finished name='Task-115' coro=<bucket_template._check_bucket_exists() done, defined at /home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/bbot/modules/templates/bucket.py:93> exception=IDNAError('Invalid A-label')>
Traceback (most recent call last):
  File "/usr/lib/python3.11/encodings/punycode.py", line 134, in decode_generalized_number
    char = ord(extended[extpos])
               ~~~~~~~~^^^^^^^^
IndexError: string index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/encodings/punycode.py", line 207, in decode
    res = punycode_decode(input, errors)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/encodings/punycode.py", line 194, in punycode_decode
    return insertion_sort(base, extended, errors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/encodings/punycode.py", line 164, in insertion_sort
    newpos, delta = decode_generalized_number(extended, extpos,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/encodings/punycode.py", line 137, in decode_generalized_number
    raise UnicodeError("incomplete punicode string")
UnicodeError: incomplete punicode string

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/idna/core.py", line 296, in ulabel
    label = label_bytes.decode('punycode')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeError: decoding with 'punycode' codec failed (UnicodeError: incomplete punicode string)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/bbot/modules/templates/bucket.py", line 95, in _check_bucket_exists
    return await self.check_bucket_exists(bucket_name, url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/bbot/modules/templates/bucket.py", line 98, in check_bucket_exists
    response = await self.helpers.request(url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/bbot/core/helpers/web.py", line 229, in request
    response = await client.request(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/bbot/core/helpers/web.py", line 87, in request
    return await super().request(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/httpx/_client.py", line 1546, in request
    request = self.build_request(
              ^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/bbot/core/helpers/web.py", line 90, in build_request
    request = super().build_request(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/httpx/_client.py", line 359, in build_request
    return Request(
           ^^^^^^^^
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/httpx/_models.py", line 349, in __init__
    self._prepare(headers)
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/httpx/_models.py", line 385, in _prepare
    if not has_host and self.url.host:
                        ^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/httpx/_urls.py", line 189, in host
    host = idna.decode(host)
           ^^^^^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/idna/core.py", line 388, in decode
    s = ulabel(label)
        ^^^^^^^^^^^^^
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.11/site-packages/idna/core.py", line 298, in ulabel
    raise IDNAError('Invalid A-label')
idna.core.IDNAError: Invalid A-label
```

**Comment by TheTechromancer** [comment]
Thanks for reporting this. The bug was due to mutations being generated from the punycode-encoded version of the domain. This is now fixed in https://github.com/blacklanternsecurity/bbot/pull/1273.
