### ISSUE TITLE
Bug in IIS Shortnames

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#1412]
```
[ERRR] Error in iis_shortnames.handle_event(URL("https://levelup.evilcorp.com/", module=httpx, tags={'cdn-github', 'status-403', 'in-scope', 'dir', 'http-title-web-app-unavailable', 'ip-20-119-16-12'})): /root/bbot/bbot/modules/iis_shortnames.py:57:detect(): 'NoneType' object has no attribute 'status_code'
2024-05-28 13:56:43,329 [TRACE] bbot.scanner logger.py:132 Traceback (most recent call last):
  File "/root/bbot/bbot/scanner/scanner.py", line 1125, in _acatch
    yield                                      
  File "/root/bbot/bbot/modules/base.py", line 635, in _worker
    await self.handle_event(event)
  File "/root/bbot/bbot/modules/iis_shortnames.py", line 224, in handle_event
    detections = await self.detect(normalized_url)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/bbot/bbot/modules/iis_shortnames.py", line 57, in detect
    if control.status_code != test.status_code: 
       ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'status_code'
```

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/1416.
