### ISSUE TITLE
Bug in BadDNS

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#1413]
```
[ERRR] Error in baddns.handle_event(DNS_NAME("www.store.evilcorp.com", module=dnsbrute, tags={'mx-error', 'subdomain', 'in-scope', 'ns-error', 'cname-record', 'a-record', 'srv-error', 'soa-error'})): /root/.cache/pypoetry/virtualenvs/bbot-aKeTQkGo-py3.11/lib/python3.11/site-packages/dns/resolver.py:763:next_nameserver(): All nameservers failed to answer the query tpgdejq.x.incapdns.net. IN CNAME: Server Do53:1.0.0.1@53 answered SERVFAIL; Server Do53:1.1.1.1@53 answered SERVFAIL
[ERRR] Task exception was never retrieved
future: <Task finished name='Task-59018' coro=<BadDNS_cname.dispatch() done, defined at /root/.cache/pypoetry/virtualenvs/bbot-aKeTQkGo-py3.11/lib/python3.11/site-packages/baddns/modules/cname.py:31> exception=NoNameservers('All nameservers failed to answer the query tpgdejq.x.incapdns.net. IN CNAME: Server Do53:1.0.0.1@53 answered SERVFAIL; Server Do53:1.1.1.1@53 answered SERVFAIL')>
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/bbot-aKeTQkGo-py3.11/lib/python3.11/site-packages/baddns/modules/cname.py", line 32, in dispatch
    await self.target_dnsmanager.dispatchDNS()
  File "/root/.cache/pypoetry/virtualenvs/bbot-aKeTQkGo-py3.11/lib/python3.11/site-packages/baddns/lib/dnsmanager.py", line 143, in dispatchDNS
    self.answers[rdatatype] = await task
                              ^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/bbot-aKeTQkGo-py3.11/lib/python3.11/site-packages/baddns/lib/dnsmanager.py", line 120, in do_resolve
    r = self.process_answer(await self.dns_client.resolve(target, "CNAME"), "CNAME")
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/bbot-aKeTQkGo-py3.11/lib/python3.11/site-packages/dns/asyncresolver.py", line 86, in resolve
    (nameserver, tcp, backoff) = resolution.next_nameserver()
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/bbot-aKeTQkGo-py3.11/lib/python3.11/site-packages/dns/resolver.py", line 763, in next_nameserver
    raise NoNameservers(request=self.request, errors=self.errors)
dns.resolver.NoNameservers: All nameservers failed to answer the query tpgdejq.x.incapdns.net. IN CNAME: Server Do53:1.0.0.1@53 answered SERVFAIL; Server Do53:1.1.1.1@53 answered SERVFAIL
```

**Comment by TheTechromancer** [comment]
Seems to be fixed now.
