### ISSUE TITLE
ASN Error

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#1415]
```
2024-05-28 19:46:58,401 [ERROR] bbot.scanner scanner.py:1145 Error in asn.handle_event(IP_ADDRESS("149.72.0.0", module=TXT, tags={'internal', 'distance-1', 'ptr-error', 'ipv4'})): /home/bls/Downloads/code/bbot/bbot/modules/report/asn.py:41:handle_event(): not enough values to unpack (expected 2, got 0)
2024-05-28 19:46:58,402 [TRACE] bbot.scanner logger.py:132 Traceback (most recent call last):
  File "/home/bls/Downloads/code/bbot/bbot/scanner/scanner.py", line 1125, in _acatch
    yield
  File "/home/bls/Downloads/code/bbot/bbot/modules/base.py", line 635, in _worker
    await self.handle_event(event)
  File "/home/bls/Downloads/code/bbot/bbot/modules/report/asn.py", line 41, in handle_event
    asns, source = await self.get_asn(host)
    ^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 0)
```

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/1416.
