### ISSUE TITLE
Excavate error

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#1542]
```
2024-07-08 16:43:49,966 [ERROR] bbot.scanner scanner.py:1184 Error in excavate.handle_event(HTTP_RESPONSE("{'url': 'https://evilcorp.com/', 'timestamp': '2024-07-08T16:38:01....
", module=httpx, tags={'ip-172-64-155-37', 'dir', 'status-200', 'in-scope', 'cdn-cloudflare', 'http-title-home-evilcorp'})): /home/azureuser/bbot/bbot/modules/internal/excavate.p
y:891:search(): 'utf-8' codec can't encode characters in position 160015-160016: surrogates not allowed
2024-07-08 16:43:49,967 [TRACE] bbot.scanner logger.py:132 Traceback (most recent call last):
  File "/home/azureuser/bbot/bbot/scanner/scanner.py", line 1164, in _acatch
    yield
  File "/home/azureuser/bbot/bbot/modules/base.py", line 636, in _worker
    await self.handle_event(event)
  File "/home/azureuser/bbot/bbot/modules/internal/excavate.py", line 1013, in handle_event
    await self.search(
  File "/home/azureuser/bbot/bbot/modules/internal/excavate.py", line 891, in search
    for result in self.yara_rules.match(data=f"{data}\n{decoded_data}"):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 160015-160016: surrogates not allowed
```

**Comment by liquidsec** [comment]
fixed in https://github.com/blacklanternsecurity/bbot/pull/1546
