### ISSUE TITLE
IIS Shortnames max_node_count exceeded

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#1549]
Against certain sites, the following message will repeat many hundreds of times:

```
[WARN] iis_shortnames: iis_shortnames: max_node_count (50) exceeded for node: http://www.evilcorp.com/. Affected branch will be terminated.
[WARN] iis_shortnames: iis_shortnames: max_node_count (50) exceeded for node: http://www.evilcorp.com/. Affected branch will be terminated.
[WARN] iis_shortnames: iis_shortnames: max_node_count (50) exceeded for node: http://www.evilcorp.com/. Affected branch will be terminated.
[WARN] iis_shortnames: iis_shortnames: max_node_count (50) exceeded for node: http://www.evilcorp.com/. Affected branch will be terminated.
[WARN] iis_shortnames: iis_shortnames: max_node_count (50) exceeded for node: http://www.evilcorp.com/. Affected branch will be terminated.
[WARN] iis_shortnames: iis_shortnames: max_node_count (50) exceeded for node: http://www.evilcorp.com/. Affected branch will be terminated.
[WARN] iis_shortnames: iis_shortnames: max_node_count (50) exceeded for node: http://www.evilcorp.com/. Affected branch will be terminated.
[WARN] iis_shortnames: iis_shortnames: max_node_count (50) exceeded for node: http://www.evilcorp.com/. Affected branch will be terminated.
[WARN] iis_shortnames: iis_shortnames: max_node_count (50) exceeded for node: http://www.evilcorp.com/. Affected branch will be terminated.
[WARN] iis_shortnames: iis_shortnames: max_node_count (50) exceeded for node: http://www.evilcorp.com/. Affected branch will be terminated.
[WARN] iis_shortnames: iis_shortnames: max_node_count (50) exceeded for node: http://www.evilcorp.com/. Affected branch will be terminated.
[WARN] iis_shortnames: iis_shortnames: max_node_count (50) exceeded for node: http://www.evilcorp.com/. Affected branch will be terminated.
[WARN] iis_shortnames: iis_shortnames: max_node_count (50) exceeded for node: http://www.evilcorp.com/. Affected branch will be terminated.
[WARN] iis_shortnames: iis_shortnames: max_node_count (50) exceeded for node: http://www.evilcorp.com/. Affected branch will be terminated.
[WARN] iis_shortnames: iis_shortnames: max_node_count (50) exceeded for node: http://www.evilcorp.com/. Affected branch will be terminated.
[WARN] iis_shortnames: iis_shortnames: max_node_count (50) exceeded for node: http://www.evilcorp.com/. Affected branch will be terminated.
[WARN] iis_shortnames: iis_shortnames: max_node_count (50) exceeded for node: http://www.evilcorp.com/. Affected branch will be terminated.
[WARN] iis_shortnames: iis_shortnames: max_node_count (50) exceeded for node: http://www.evilcorp.com/. Affected branch will be terminated.
[WARN] iis_shortnames: iis_shortnames: max_node_count (50) exceeded for node: http://www.evilcorp.com/. Affected branch will be terminated.
[WARN] iis_shortnames: iis_shortnames: max_node_count (50) exceeded for node: http://www.evilcorp.com/. Affected branch will be terminated.
[WARN] iis_shortnames: iis_shortnames: max_node_count (50) exceeded for node: http://www.evilcorp.com/. Affected branch will be terminated.
[WARN] iis_shortnames: iis_shortnames: max_node_count (50) exceeded for node: http://www.evilcorp.com/. Affected branch will be terminated.
[WARN] iis_shortnames: iis_shortnames: max_node_count (50) exceeded for node: http://www.evilcorp.com/. Affected branch will be terminated.
[WARN] iis_shortnames: iis_shortnames: max_node_count (50) exceeded for node: http://www.evilcorp.com/. Affected branch will be terminated.
[WARN] iis_shortnames: iis_shortnames: max_node_count (50) exceeded for node: http://www.evilcorp.com/. Affected branch will be terminated.
[WARN] iis_shortnames: iis_shortnames: max_node_count (50) exceeded for node: http://www.evilcorp.com/. Affected branch will be terminated.
[WARN] iis_shortnames: iis_shortnames: max_node_count (50) exceeded for node: http://www.evilcorp.com/. Affected branch will be terminated.
```

**Comment by TheTechromancer** [comment]
It did finally abort after the message was printed 1,477 times:

```
2024-07-09 16:28:02,878 [WARNING] bbot.modules.iis_shortnames base.py:1346 iis_shortnames: max_node_count (50) exceeded for node: http://www.evilcorp.com/. Affected branch will be terminated.
2024-07-09 16:28:02,879 [WARNING] bbot.modules.iis_shortnames base.py:1346 Aborted Shortname Run for URL [http://www.evilcorp.com/] due to Error: [Exceeded safety counter threshold (3001)]
2024-07-09 16:28:02,882 [TRACE] bbot.modules.iis_shortnames logger.py:132 Traceback (most recent call last):
  File "/home/azureuser/bbot/bbot/modules/iis_shortnames.py", line 268, in handle_event
    await self.solve_shortname_recursive(
  File "/home/azureuser/bbot/bbot/modules/iis_shortnames.py", line 200, in solve_shortname_recursive
    url_hint_list += await self.solve_shortname_recursive(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azureuser/bbot/bbot/modules/iis_shortnames.py", line 200, in solve_shortname_recursive
    url_hint_list += await self.solve_shortname_recursive(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azureuser/bbot/bbot/modules/iis_shortnames.py", line 200, in solve_shortname_recursive
    url_hint_list += await self.solve_shortname_recursive(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 39 more times]
  File "/home/azureuser/bbot/bbot/modules/iis_shortnames.py", line 181, in solve_shortname_recursive
    raise IISShortnamesError(f"Exceeded safety counter threshold ({safety_counter.counter})")
bbot.modules.iis_shortnames.IISShortnamesError: Exceeded safety counter threshold (3001)
```

**Comment by liquidsec** [comment]
fixed in https://github.com/blacklanternsecurity/bbot/pull/1552
