### ISSUE TITLE
github_workflows: error in download() helper

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#1727]
```
2024-09-01 00:58:36,420 [ERROR] bbot.core.httpengine engine.py:425 EngineServer HTTPEngine: error in download(('https://api.github.com/repos/duckduckgo/tracker-radar-wiki/actions/runs/9546154550/logs',), {'headers': {'Authorization': 'token xxxx'}, 'raise_error': True, 'warn': False, 'filename': PosixPath('/root/.bbot/scans/plastered_wayne/workflow_logs/duckduckgo/tracker-radar-wiki/run_9546154550.zip')}): Client error '403 Forbidden' for url 'https://api.github.com/repos/duckduckgo/tracker-radar-wiki/actions/runs/9546154550/logs'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403
2024-09-01 00:58:36,420 [TRACE] bbot.core.httpengine logger.py:132 Traceback (most recent call last):
  File "/root/bbot/bbot/core/engine.py", line 417, in run_and_return
    result = await command_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/bbot/bbot/core/helpers/web/engine.py", line 116, in download
    response.raise_for_status()
  File "/root/.cache/pypoetry/virtualenvs/bbot-aKeTQkGo-py3.12/lib/python3.12/site-packages/httpx/_models.py", line 759, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '403 Forbidden' for url 'https://api.github.com/repos/duckduckgo/tracker-radar-wiki/actions/runs/9546154550/logs'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403

2024-09-01 00:58:36,421 [INFO] bbot.modules.github_workflows base.py:1283 The logs for duckduckgo/tracker-radar-wiki/9546154550 have expired and are no longer available (status: 0)
```

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/1728.
