### ISSUE TITLE
Portscan bug

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#1779]
```
2024-09-17 13:55:44,266 [ERROR] bbot.scanner scanner.py:1203 Error in portscan.handle_batch(): /root/bbot/bbot/core/helpers/misc.py:230:split_host_port(): split_port() failed to parse netloc
 "::"                                                                                                                                                                                         
2024-09-17 13:55:44,266 [TRACE] bbot.scanner logger.py:132 Traceback (most recent call last):                                                                                                 
  File "/root/bbot/bbot/scanner/scanner.py", line 1180, in _acatch                                                                                                                            
    yield
  File "/root/bbot/bbot/modules/base.py", line 401, in _handle_batch
    await self.handle_batch(*events)
  File "/root/bbot/bbot/modules/portscan.py", line 110, in handle_batch
    syn_targets, syn_correlator = await self.make_targets(events, self.syn_scanned)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/bbot/bbot/modules/portscan.py", line 199, in make_targets
    if not scanned_tracker.get(ip):
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/bbot/bbot/scanner/target.py", line 402, in get
    event = make_event(host, dummy=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/bbot/bbot/core/event/base.py", line 1655, in make_event
    return event_class(
           ^^^^^^^^^^^^
  File "/root/bbot/bbot/core/event/base.py", line 1101, in __init__
    super().__init__(*args, **kwargs)
  File "/root/bbot/bbot/core/event/base.py", line 1087, in __init__
    if is_subdomain(self.host):
       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/bbot/bbot/core/helpers/misc.py", line 84, in is_subdomain
    d, _ = split_host_port(d)
           ^^^^^^^^^^^^^^^^^^
  File "/root/bbot/bbot/core/helpers/misc.py", line 230, in split_host_port
    raise ValueError(f'split_port() failed to parse netloc "{netloc}"')
ValueError: split_port() failed to parse netloc "::"
```

**Comment by liquidsec** [comment]
this was fixed at some point, it is confirmed to not be an issue on 3.0.
