### ISSUE TITLE
after install on windows error  Failed to set new ulimit: No module named 'resource'

### ISSUE THREAD

**Issue by jinji9630** [blacklanternsecurity/bbot#1841]
bbot.exe -t honda.com
  ______  _____   ____ _______
 |  ___ \|  __ \ / __ \__   __|
 | |___) | |__) | |  | | | |
 |  ___ <|  __ <| |  | | | |
 | |___) | |__) | |__| | | |
 |______/|_____/ \____/  |_|
 BIGHUGE BLS OSINT TOOL v2.0.1

www.blacklanternsecurity.com/bbot

Failed to set new ulimit: No module named 'resource'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\users\administrator\.local\bin\bbot.exe\__main__.py", line 7, in <module>
  File "C:\Users\Administrator\pipx\venvs\bbot\Lib\site-packages\bbot\cli.py", line 272, in main
    asyncio.run(_main())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\pipx\venvs\bbot\Lib\site-packages\bbot\cli.py", line 168, in _main
    scan.helpers.word_cloud.load()
    ^^^^^^^^^^^^
  File "C:\Users\Administrator\pipx\venvs\bbot\Lib\site-packages\bbot\scanner\scanner.py", line 861, in helpers
    return self.preset.helpers
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\pipx\venvs\bbot\Lib\site-packages\bbot\scanner\preset\preset.py", line 560, in helpers
    from bbot.core.helpers.helper import ConfigAwareHelper
  File "C:\Users\Administrator\pipx\venvs\bbot\Lib\site-packages\bbot\core\helpers\helper.py", line 16, in <module>
    from .depsinstaller import DepsInstaller
  File "C:\Users\Administrator\pipx\venvs\bbot\Lib\site-packages\bbot\core\helpers\depsinstaller\__init__.py", line 1, in <module>
    from .installer import DepsInstaller
  File "C:\Users\Administrator\pipx\venvs\bbot\Lib\site-packages\bbot\core\helpers\depsinstaller\installer.py", line 13, in <module>
    from ansible_runner.interface import run
  File "C:\Users\Administrator\pipx\venvs\bbot\Lib\site-packages\ansible_runner\__init__.py", line 1, in <module>
    from .utils.importlib_compat import importlib_metadata
  File "C:\Users\Administrator\pipx\venvs\bbot\Lib\site-packages\ansible_runner\utils\__init__.py", line 9, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'

**Comment by TheTechromancer** [comment]
Windows is not supported. Please run in WSL or use docker.

https://www.blacklanternsecurity.com/bbot/Stable/
