### ISSUE TITLE
Logging bug with tests

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#1895]
This bug causes the pytest binary to exit with a bad status even though all the tests pass.

```
-------------------------------- live log call ---------------------------------
INFO     bbot.test.subdomainenumwildcarddefense:base.py:116 Finished subdomainenumwildcarddefense module test
INFO     bbot.test.subdomainenumwildcarddefense:base.py:122 No unfinished tasks detected
[INFO] No unfinished tasks detected
PASSED                                                                   [100%]

Test Session Summary:
Total tests run: 315
Passed: 314, Failed: 0, Skipped: 1, Errors: 0
====== 314 passed, 1 skipped, 73 warnings, 1 rerun in 1665.79s (0:27:45) =======
Exception in thread Thread-1 (_monitor):
Traceback (most recent call last):
  File "/github/home/.pyenv/versions/3.11.10/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/github/home/.pyenv/versions/3.11.10/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/github/home/.pyenv/versions/3.11.10/lib/python3.11/logging/handlers.py", line 1573, in _monitor
    record = self.dequeue(True)
             ^^^^^^^^^^^^^^^^^^
  File "/github/home/.pyenv/versions/3.11.10/lib/python3.11/logging/handlers.py", line 1522, in dequeue
    return self.queue.get(block)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/github/home/.pyenv/versions/3.11.10/lib/python3.11/multiprocessing/queues.py", line 103, in get
    res = self._recv_bytes()
          ^^^^^^^^^^^^^^^^^^
  File "/github/home/.pyenv/versions/3.11.10/lib/python3.11/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/github/home/.pyenv/versions/3.11.10/lib/python3.11/multiprocessing/connection.py", line 430, in _recv_bytes
    buf = self._recv(4)
Fatal Python error: _enter_buffered_busy: could not acquire lock for <_io.BufferedWriter name='<stderr>'> at interpreter shutdown, possibly due to daemon threads
Python runtime state: finalizing (tstate=0x00007fcec638c678)

Current thread 0x00007fcec646eb80 (most recent call first):
  <no Python frame>

Extension modules: markupsafe._speedups, yaml._yaml, regex._regex, _cffi_backend, charset_normalizer.md, requests.packages.charset_normalizer.md, requests.packages.chardet.md, zmq.backend.cython._zmq, yara, lxml._elementpath, lxml.etree, mmh3, setproctitle._setproctitle, multidict._multidict, yarl._quoting_c, propcache._helpers_c, aiohttp._helpers, aiohttp._http_writer, aiohttp._http_parser, aiohttp._websocket, frozenlist._frozenlist, psutil._psutil_linux, psutil._psutil_posix, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, pandas._libs.tslibs.ccalendar, pandas._libs.tslibs.np_datetime, pandas._libs.tslibs.dtypes, pandas._libs.tslibs.base, pandas._libs.tslibs.nattype, pandas._libs.tslibs.timezones, pandas._libs.tslibs.fields, pandas._libs.tslibs.timedeltas, pandas._libs.tslibs.tzconversion, pandas._libs.tslibs.timestamps, pandas._libs.properties, pandas._libs.tslibs.offsets, pandas._libs.tslibs.strptime, pandas._libs.tslibs.parsing, pandas._libs.tslibs.conversion, pandas._libs.tslibs.period, pandas._libs.tslibs.vectorized, pandas._libs.ops_dispatch, pandas._libs.missing, pandas._libs.hashtable, pandas._libs.algos, pandas._libs.interval, pandas._libs.lib, pandas._libs.ops, pandas._libs.hashing, pandas._libs.arrays, pandas._libs.tslib, pandas._libs.sparse, pandas._libs.internals, pandas._libs.indexing, pandas._libs.index, pandas._libs.writers, pandas._libs.join, pandas._libs.window.aggregations, pandas._libs.window.indexers, pandas._libs.reshape, pandas._libs.groupby, pandas._libs.json, pandas._libs.parsers, pandas._libs.testing, websockets.speedups (total: 77)
Aborted (core dumped)
Error: Process completed with exit code 134.
```

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/1896.
