### ISSUE TITLE
RuntimeError('Event loop is closed') on scan completion

### ISSUE THREAD

**Issue by liquidsec** [blacklanternsecurity/bbot#1898]
Error:

```
[INFO] Finishing scan
[VERB] Completed finish()
[VERB] Completed final finish()
[SCAN]              	violent_ronald (SCAN:871d48ae66894d2e9cff40d646346e71593fdd3e)	TARGET	(in-scope)
[SUCC] Scan violent_ronald completed in 25 minutes, 35 seconds with status FINISHED
[INFO] aggregate: +-----------------+-----------------------------------+-----------------------------------------+
[INFO] aggregate: | Module          | Produced                          | Consumed                                |
[INFO] aggregate: +=================+===================================+=========================================+
[INFO] aggregate: | iis_shortnames  | 46 (44 URL_HINT, 2 VULNERABILITY) | 3 (3 URL)                               |
[INFO] aggregate: +-----------------+-----------------------------------+-----------------------------------------+
[INFO] aggregate: | httpx           | 4 (4 URL)                         | 4 (2 OPEN_TCP_PORT, 2 URL_UNVERIFIED)   |
[INFO] aggregate: +-----------------+-----------------------------------+-----------------------------------------+
[INFO] aggregate: | speculate       | 3 (2 OPEN_TCP_PORT, 1 ORG_STUB)   | 21 (3 DNS_NAME, 4 HTTP_RESPONSE, 4      |
[INFO] aggregate: |                 |                                   | IP_ADDRESS, 4 URL, 6 URL_UNVERIFIED)    |
[INFO] aggregate: +-----------------+-----------------------------------+-----------------------------------------+
[INFO] aggregate: | host            | 2 (2 DNS_NAME)                    | 0                                       |
[INFO] aggregate: +-----------------+-----------------------------------+-----------------------------------------+
[INFO] aggregate: | excavate        | 1 (1 DNS_NAME)                    | 4 (4 HTTP_RESPONSE)                     |
[INFO] aggregate: +-----------------+-----------------------------------+-----------------------------------------+
[INFO] aggregate: | dnsresolve      | 0                                 | 89 (6 DNS_NAME, 4 HTTP_RESPONSE, 4      |
[INFO] aggregate: |                 |                                   | IP_ADDRESS, 16 OPEN_TCP_PORT, 4 URL, 44 |
[INFO] aggregate: |                 |                                   | URL_HINT, 9 URL_UNVERIFIED, 2           |
[INFO] aggregate: |                 |                                   | VULNERABILITY)                          |
[INFO] aggregate: +-----------------+-----------------------------------+-----------------------------------------+
[INFO] aggregate: | cloudcheck      | 0                                 | 88 (5 DNS_NAME, 4 HTTP_RESPONSE, 4      |
[INFO] aggregate: |                 |                                   | IP_ADDRESS, 16 OPEN_TCP_PORT, 4 URL, 44 |
[INFO] aggregate: |                 |                                   | URL_HINT, 9 URL_UNVERIFIED, 2           |
[INFO] aggregate: |                 |                                   | VULNERABILITY)                          |
[INFO] aggregate: +-----------------+-----------------------------------+-----------------------------------------+
[INFO] aggregate: | ffuf_shortnames | 0                                 | 44 (44 URL_HINT)                        |
[INFO] aggregate: +-----------------+-----------------------------------+-----------------------------------------+
[VERB] aggregate: Wrote scan-stats to /home/redacted/.bbot/scans/violent_ronald/scan-stats-table-20241029_2156_55.txt
[INFO] output.csv: Saved CSV output to /home/redacted/.bbot/scans/violent_ronald/output.csv
[INFO] output.json: Saved JSON output to /home/redacted/.bbot/scans/violent_ronald/output.json
[INFO] output.txt: Saved TXT output to /home/redacted/.bbot/scans/violent_ronald/output.txt
[VERB] EngineClient DNSHelper: shutting down...
[VERB] EngineClient WebHelper: shutting down...
[INFO] Saved word cloud (29 words) to /home/redacted/.bbot/scans/violent_ronald/wordcloud.tsv
Loop <_UnixSelectorEventLoop running=False closed=True debug=False> that handles pid 393578 is closed
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x7fd7fd1c4ae0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/asyncio/base_subprocess.py", line 126, in __del__
    self.close()
  File "/usr/local/lib/python3.11/asyncio/base_subprocess.py", line 104, in close
    proto.pipe.close()
  File "/usr/local/lib/python3.11/asyncio/unix_events.py", line 566, in close
    self._close(None)
  File "/usr/local/lib/python3.11/asyncio/unix_events.py", line 590, in _close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 761, in call_soon
    self._check_closed()
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by liquidsec** [comment]
obsolete, since event loop has been significantly rewritten since 2024.
