### ISSUE TITLE
TypeError: argument of type 'BBOTTarget' is not iterable

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#2001]
```
[ERRR] myssl: Unhandled exception in myssl.filter_event(DNS_NAME("evilcorp.com", module=otx, tags={'subdomain', 'cloud-google', 'in-scope', 'a-record'})): argument of type 'BBOTTarget' is not iterable
[TRCE] myssl: Traceback (most recent call last):                                                         
  File "/root/bbot/bbot/modules/base.py", line 807, in _event_postcheck_inner                            
    filter_result = await self.filter_event(event)                                                       
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                       
  File "/root/bbot/bbot/modules/templates/subdomain_enum.py", line 172, in filter_event                                                                                                                            
    if is_cloud and event not in self.scan.target:                                                       
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                        
TypeError: argument of type 'BBOTTarget' is not iterable
```

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/2002.
