### ISSUE TITLE
Interact.sh poll error

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#201]
```bash
bbot -f web-basic web-advanced -m ffuf --allow-deadly -t http://www.evilcorp.com

...

[ERRR] bbot.scanner.manager: Error in Interactsh._poll_loop(): Missing required information to poll
[DBUG] bbot.scanner.manager: Traceback (most recent call last):
  File "/home/user/bbot/scanner/manager.py", line 294, in catch
    ret = callback(*args, **kwargs)
  File "/home/user/bbot/core/helpers/interactsh.py", line 129, in _poll_loop
    data_list = list(self.poll())
  File "/home/user/bbot/core/helpers/interactsh.py", line 102, in poll
    raise InteractshError(f"Missing required information to poll")
bbot.core.errors.InteractshError: Missing required information to poll
```

**Comment by TheTechromancer** [comment]
Fixed https://github.com/blacklanternsecurity/bbot/pull/202
