### ISSUE TITLE
Test Errors

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#2059]
Recently we've run into some strange errors in our Kali tests.

```
2024-12-05T19:15:40.0760047Z bbot/test/test_step_2/module_tests/test_module_web_report.py::TestWebReport::test_module_run ERROR [ 97%]
2024-12-05T19:15:44.7266465Z Traceback (most recent call last):
2024-12-05T19:15:44.7267557Z   File "/github/home/.pyenv/versions/3.11.11/lib/python3.11/multiprocessing/queues.py", line 244, in _feed
2024-12-05T19:15:44.7268602Z     obj = _ForkingPickler.dumps(obj)
2024-12-05T19:15:44.7269084Z           ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-05T19:15:44.7269903Z   File "/github/home/.pyenv/versions/3.11.11/lib/python3.11/multiprocessing/reduction.py", line 51, in dumps
2024-12-05T19:15:44.7270866Z     cls(buf, protocol).dump(obj)
2024-12-05T19:15:44.7271327Z TypeError: cannot pickle 'TaskStepMethWrapper' object
```

Lots of orphaned DNSEngine servers:
```
2024-12-05T19:17:33.3924328Z = 14 failed, 202 passed, 3 skipped, 14 warnings, 110 errors, 248 rerun in 4205.30s (1:10:05) =
2024-12-05T19:17:33.3924437Z === Detailed Thread and Process Information ===
2024-12-05T19:17:33.3924443Z 
2024-12-05T19:17:33.3924508Z === Threads ===
2024-12-05T19:17:33.3924637Z Thread Name: MainThread
2024-12-05T19:17:33.3924714Z Thread ID: 139876764756864
2024-12-05T19:17:33.3924778Z Is Alive: True
2024-12-05T19:17:33.3924843Z Daemon: False
2024-12-05T19:17:33.3924921Z Target Function: None
2024-12-05T19:17:33.3924926Z 
2024-12-05T19:17:33.3925005Z Thread Name: Thread-1 (_monitor)
2024-12-05T19:17:33.3925080Z Thread ID: 139876710745792
2024-12-05T19:17:33.3925145Z Is Alive: True
2024-12-05T19:17:33.3925211Z Daemon: True
2024-12-05T19:17:33.3925355Z Target Function: logging.handlers.QueueListener._monitor
2024-12-05T19:17:33.3925419Z Arguments:
2024-12-05T19:17:33.3925423Z 
2024-12-05T19:17:33.3925503Z Thread Name: QueueFeederThread
2024-12-05T19:17:33.3925577Z Thread ID: 139876603840192
2024-12-05T19:17:33.3925641Z Is Alive: True
2024-12-05T19:17:33.3925705Z Daemon: True
2024-12-05T19:17:33.3925887Z Target Function: multiprocessing.queues.Queue._feed
2024-12-05T19:17:33.3925953Z Arguments:
2024-12-05T19:17:33.3926100Z   buffer: deque([])
2024-12-05T19:17:33.3926393Z   notempty: <Condition(<unlocked _thread.lock object at 0x7f3795cf08c0>, 1)>
2024-12-05T19:17:33.3926831Z   send_bytes: <bound method _ConnectionBase.send_bytes of <multiprocessing.connection.Connection object at 0x7f379612ad10>>
2024-12-05T19:17:33.3926912Z   writelock: <Lock(owner=None)>
2024-12-05T19:17:33.3927246Z   reader_close: <bound method _ConnectionBase.close of <multiprocessing.connection.Connection object at 0x7f3795de91d0>>
2024-12-05T19:17:33.3927562Z   writer_close: <bound method _ConnectionBase.close of <multiprocessing.connection.Connection object at 0x7f379612ad10>>
2024-12-05T19:17:33.3927634Z   ignore_epipe: False
2024-12-05T19:17:33.3927807Z   onerror: <function Queue._on_queue_feeder_error at 0x7f3795cb4540>
2024-12-05T19:17:33.3928070Z   queue_sem: <BoundedSemaphore(value=2147483647, maxvalue=2147483647)>
2024-12-05T19:17:33.3928078Z 
2024-12-05T19:17:33.3928176Z Thread Name: Thread-94 (server_process)
2024-12-05T19:17:33.3928248Z Thread ID: 139875944756928
2024-12-05T19:17:33.3928315Z Is Alive: True
2024-12-05T19:17:33.3928387Z Daemon: True
2024-12-05T19:17:33.3928544Z Target Function: bbot.core.engine.EngineClient.server_process
2024-12-05T19:17:33.3928612Z Arguments:
2024-12-05T19:17:33.3928827Z   server_class: <class 'bbot.core.helpers.dns.engine.DNSEngine'>
2024-12-05T19:17:33.3928950Z   socket_path: /tmp/zmq_3nwnrflm.sock
2024-12-05T19:17:33.3928954Z 
2024-12-05T19:17:33.3929043Z Thread Name: Thread-97 (server_process)
2024-12-05T19:17:33.3929118Z Thread ID: 139875240105664
2024-12-05T19:17:33.3929183Z Is Alive: True
2024-12-05T19:17:33.3929245Z Daemon: True
2024-12-05T19:17:33.3929415Z Target Function: bbot.core.engine.EngineClient.server_process
2024-12-05T19:17:33.3929524Z Arguments:
2024-12-05T19:17:33.3929748Z   server_class: <class 'bbot.core.helpers.dns.engine.DNSEngine'>
2024-12-05T19:17:33.3929846Z   socket_path: /tmp/zmq_7rxn6y0g.sock
2024-12-05T19:17:33.3929850Z 
2024-12-05T19:17:33.3929940Z Thread Name: Thread-100 (server_process)
2024-12-05T19:17:33.3930009Z Thread ID: 139874961241792
2024-12-05T19:17:33.3930082Z Is Alive: True
2024-12-05T19:17:33.3930147Z Daemon: True
2024-12-05T19:17:33.3930295Z Target Function: bbot.core.engine.EngineClient.server_process
2024-12-05T19:17:33.3930365Z Arguments:
2024-12-05T19:17:33.3930607Z   server_class: <class 'bbot.core.helpers.dns.engine.DNSEngine'>
2024-12-05T19:17:33.3930694Z   socket_path: /tmp/zmq_995q34e2.sock
2024-12-05T19:17:33.3930698Z 
2024-12-05T19:17:33.3930781Z Thread Name: Thread-103 (server_process)
2024-12-05T19:17:33.3930848Z Thread ID: 139875273668288
2024-12-05T19:17:33.3930919Z Is Alive: True
2024-12-05T19:17:33.3930981Z Daemon: True
2024-12-05T19:17:33.3931127Z Target Function: bbot.core.engine.EngineClient.server_process
2024-12-05T19:17:33.3931194Z Arguments:
2024-12-05T19:17:33.3931339Z   server_class: <class 'bbot.core.helpers.dns.engine.DNSEngine'>
2024-12-05T19:17:33.3931420Z   socket_path: /tmp/zmq_jq56fi7h.sock
2024-12-05T19:17:33.3931425Z 
2024-12-05T19:17:33.3931513Z Thread Name: Thread-106 (server_process)
2024-12-05T19:17:33.3931643Z Thread ID: 139874652907200
2024-12-05T19:17:33.3931708Z Is Alive: True
2024-12-05T19:17:33.3931778Z Daemon: True
2024-12-05T19:17:33.3931936Z Target Function: bbot.core.engine.EngineClient.server_process
2024-12-05T19:17:33.3932050Z Arguments:
2024-12-05T19:17:33.3932277Z   server_class: <class 'bbot.core.helpers.dns.engine.DNSEngine'>
2024-12-05T19:17:33.3932359Z   socket_path: /tmp/zmq_f621mco8.sock
2024-12-05T19:17:33.3932363Z 
2024-12-05T19:17:33.3932497Z Thread Name: Thread-109 (server_process)
2024-12-05T19:17:33.3932622Z Thread ID: 139874569000640
2024-12-05T19:17:33.3932710Z Is Alive: True
2024-12-05T19:17:33.3932780Z Daemon: True
2024-12-05T19:17:33.3932929Z Target Function: bbot.core.engine.EngineClient.server_process
2024-12-05T19:17:33.3932991Z Arguments:
2024-12-05T19:17:33.3933236Z   server_class: <class 'bbot.core.helpers.dns.engine.DNSEngine'>
2024-12-05T19:17:33.3933370Z   socket_path: /tmp/zmq_zuxzy2px.sock
2024-12-05T19:17:33.3933375Z 
2024-12-05T19:17:33.3933460Z Thread Name: Thread-112 (server_process)
2024-12-05T19:17:33.3933537Z Thread ID: 139874183145152
2024-12-05T19:17:33.3933600Z Is Alive: True
2024-12-05T19:17:33.3933664Z Daemon: True
2024-12-05T19:17:33.3933817Z Target Function: bbot.core.engine.EngineClient.server_process
2024-12-05T19:17:33.3933881Z Arguments:
2024-12-05T19:17:33.3934026Z   server_class: <class 'bbot.core.helpers.dns.engine.DNSEngine'>
2024-12-05T19:17:33.3934111Z   socket_path: /tmp/zmq_qd3e6kek.sock
2024-12-05T19:17:33.3934115Z 
2024-12-05T19:17:33.3934196Z Thread Name: Thread-115 (server_process)
2024-12-05T19:17:33.3934264Z Thread ID: 139873663055552
2024-12-05T19:17:33.3934337Z Is Alive: True
2024-12-05T19:17:33.3934400Z Daemon: True
2024-12-05T19:17:33.3934544Z Target Function: bbot.core.engine.EngineClient.server_process
2024-12-05T19:17:33.3934612Z Arguments:
2024-12-05T19:17:33.3934759Z   server_class: <class 'bbot.core.helpers.dns.engine.DNSEngine'>
2024-12-05T19:17:33.3934841Z   socket_path: /tmp/zmq_hkra5hlx.sock
2024-12-05T19:17:33.3934853Z 
2024-12-05T19:17:33.3934936Z Thread Name: Thread-118 (server_process)
2024-12-05T19:17:33.3935003Z Thread ID: 139873495275200
2024-12-05T19:17:33.3935073Z Is Alive: True
2024-12-05T19:17:33.3935137Z Daemon: True
2024-12-05T19:17:33.3935283Z Target Function: bbot.core.engine.EngineClient.server_process
2024-12-05T19:17:33.3935350Z Arguments:
2024-12-05T19:17:33.3935497Z   server_class: <class 'bbot.core.helpers.dns.engine.DNSEngine'>
2024-12-05T19:17:33.3935600Z   socket_path: /tmp/zmq_knkjbhca.sock
2024-12-05T19:17:33.3935605Z 
2024-12-05T19:17:33.3935759Z Thread Name: Thread-434 (server_process)
2024-12-05T19:17:33.3935860Z Thread ID: 139874910897856
2024-12-05T19:17:33.3935928Z Is Alive: True
2024-12-05T19:17:33.3935998Z Daemon: True
2024-12-05T19:17:33.3936239Z Target Function: bbot.core.engine.EngineClient.server_process
2024-12-05T19:17:33.3936305Z Arguments:
2024-12-05T19:17:33.3936543Z   server_class: <class 'bbot.core.helpers.dns.engine.DNSEngine'>
2024-12-05T19:17:33.3936626Z   socket_path: /tmp/zmq_207bravb.sock
2024-12-05T19:17:33.3936632Z 
2024-12-05T19:17:33.3936716Z Thread Name: Thread-437 (server_process)
2024-12-05T19:17:33.3936789Z Thread ID: 139873914709696
2024-12-05T19:17:33.3936854Z Is Alive: True
2024-12-05T19:17:33.3937008Z Daemon: True
2024-12-05T19:17:33.3937162Z Target Function: bbot.core.engine.EngineClient.server_process
2024-12-05T19:17:33.3937225Z Arguments:
2024-12-05T19:17:33.3937373Z   server_class: <class 'bbot.core.helpers.dns.engine.DNSEngine'>
2024-12-05T19:17:33.3937459Z   socket_path: /tmp/zmq_siv3i4ml.sock
2024-12-05T19:17:33.3937463Z 
2024-12-05T19:17:33.3937547Z Thread Name: Thread-440 (server_process)
2024-12-05T19:17:33.3937619Z Thread ID: 139873277167296
2024-12-05T19:17:33.3937684Z Is Alive: True
2024-12-05T19:17:33.3937748Z Daemon: True
2024-12-05T19:17:33.3937903Z Target Function: bbot.core.engine.EngineClient.server_process
2024-12-05T19:17:33.3937967Z Arguments:
2024-12-05T19:17:33.3938115Z   server_class: <class 'bbot.core.helpers.dns.engine.DNSEngine'>
2024-12-05T19:17:33.3938266Z   socket_path: /tmp/zmq_nd7ryew9.sock
2024-12-05T19:17:33.3938269Z 
2024-12-05T19:17:33.3938352Z Thread Name: Thread-492 (server_process)
2024-12-05T19:17:33.3938424Z Thread ID: 139874300581568
2024-12-05T19:17:33.3938497Z Is Alive: True
2024-12-05T19:17:33.3938564Z Daemon: True
2024-12-05T19:17:33.3938712Z Target Function: bbot.core.engine.EngineClient.server_process
2024-12-05T19:17:33.3938784Z Arguments:
2024-12-05T19:17:33.3938930Z   server_class: <class 'bbot.core.helpers.dns.engine.DNSEngine'>
2024-12-05T19:17:33.3939009Z   socket_path: /tmp/zmq_mehb8vr2.sock
2024-12-05T19:17:33.3939012Z 
2024-12-05T19:17:33.3939102Z Thread Name: Thread-495 (server_process)
2024-12-05T19:17:33.3939169Z Thread ID: 139873210042048
2024-12-05T19:17:33.3939234Z Is Alive: True
2024-12-05T19:17:33.3939320Z Daemon: True
2024-12-05T19:17:33.3939658Z Target Function: bbot.core.engine.EngineClient.server_process
2024-12-05T19:17:33.3939855Z Arguments:
2024-12-05T19:17:33.3940084Z   server_class: <class 'bbot.core.helpers.dns.engine.DNSEngine'>
2024-12-05T19:17:33.3940212Z   socket_path: /tmp/zmq_vgubxbea.sock
```

**Comment by liquidsec** [comment]
@TheTechromancer pretty sure these wont be relevant once blastdns is implemented?

**Comment by TheTechromancer** [comment]
Correct

**Comment by liquidsec** [comment]
not relevant anymore, blastdns is in place.
