### ISSUE TITLE
Add punycode support

### ISSUE THREAD

**Issue by man3kin3ko** [blacklanternsecurity/bbot#246]
Hello! It would be nice if you add punycode support (non-ascii domains) to bbot. Recently I tried to do it out of the box with `-t` flag, but got a following traceback:
```
[INFO] bbot: Loaded defaults from /home/kali/.local/lib/python3.10/site-packages/bbot/defaults.yml
[INFO] bbot: Loaded config from /home/kali/.config/bbot/bbot.yml
[INFO] bbot: Loaded secrets from /home/kali/.config/bbot/secrets.yml
[ERRR] bbot: Unable to autodetect event type from "<client domain>"
[ERRR] bbot: Traceback (most recent call last):
  File "/home/kali/.local/lib/python3.10/site-packages/bbot/cli.py", line 99, in main
    scanner = Scanner(
  File "/home/kali/.local/lib/python3.10/site-packages/bbot/scanner/scanner.py", line 104, in __init__
    self.target = ScanTarget(self, *targets, strict_scope=strict_scope)
  File "/home/kali/.local/lib/python3.10/site-packages/bbot/scanner/target.py", line 19, in __init__
    self.add_target(t)
  File "/home/kali/.local/lib/python3.10/site-packages/bbot/scanner/target.py", line 29, in add_target
    event = self.scan.make_event(t, source=self.scan.root_event, module=self.dummy_module, tags=["target"])
  File "/home/kali/.local/lib/python3.10/site-packages/bbot/scanner/scanner.py", line 395, in make_event
    event = make_event(*args, **kwargs)
  File "/home/kali/.local/lib/python3.10/site-packages/bbot/core/event/base.py", line 793, in make_event
    raise ValidationError(f'Unable to autodetect event type from "{data}"')
bbot.core.errors.ValidationError: Unable to autodetect event type from "<client domain>"
```

**Comment by TheTechromancer** [comment]
I agree this would be nice to have. Hopefully it would just be a matter of modifying the regexes in `bbot/core/helpers/regexes.py` to be punycode-compatible.

**Comment by TheTechromancer** [comment]
@kperevoznikova I have created an experimental branch with punycode support: https://github.com/blacklanternsecurity/bbot/pull/261.

I would appreciate if you could help us test this out. We don't have a lot of experience writing internationalized code so it will probably need a little tweaking before it's fully ready.

To test this branch you can check it out like so:
```bash
git clone https://github.com/blacklanternsecurity/bbot.git --branch punycode-support && cd bbot
pip install poetry
poetry install
poetry shell
bbot --help
```

**Comment by TheTechromancer** [comment]
These changes have been merged into `dev`.
