### ISSUE TITLE
AttributeError: 'DNSHelper' object has no attribute 'dns_resolve_distance'

### ISSUE THREAD

**Issue by liquidsec** [blacklanternsecurity/bbot#295]
2023-02-12 16:39:43,190 [INFO] bbot.scanner [scanner.py:454](http://scanner.py:454/) strained_james: Running modules: speculate, ipneighbor, excavate, asn, massdns
2023-02-12 16:39:43,190 [INFO] bbot.scanner [scanner.py:454](http://scanner.py:454/) strained_james: Events produced so far: *redacted*
2023-02-12 16:39:43,190 [INFO] bbot.scanner [scanner.py:454](http://scanner.py:454/) strained_james: 74,434 events in queue *redacted*
2023-02-12 16:39:45,167 [ERROR] bbot.scanner.manager [manager.py:308](http://manager.py:308/) Error in ScanManager._emit_event(): 'DNSHelper' object has no attribute 'dns_resolve_distance'
2023-02-12 16:39:45,172 [TRACE] bbot.scanner.manager [manager.py:309](http://manager.py:309/) Traceback (most recent call last):
  File "*/bbot/bbot/scanner/manager.py", line 302, in catch
    ret = callback(*args, **kwargs)
  File "*/bbot/bbot/scanner/manager.py", line 140, in _emit_event
    f"Skipping DNS children for {event} because their DNS resolve distances would be greater than the configured value for this scan ({self.scan.helpers.dns.dns_resolve_distance})"
AttributeError: 'DNSHelper' object has no attribute 'dns_resolve_distance'. Did you mean: 'max_dns_resolve_distance'?

**Comment by TheTechromancer** [comment]
fixed in https://github.com/blacklanternsecurity/bbot/pull/296
