### ISSUE TITLE
web_report output module KeyError

### ISSUE THREAD

**Issue by liquidsec** [blacklanternsecurity/bbot#304]
2023-02-16 04:51:01,029 [ERROR] bbot.scanner.manager manager.py:317 Error in BaseModule._if_not_errored(): 'https://redacted'
2023-02-16 04:51:01,029 [TRACE] bbot.scanner.manager manager.py:318 Traceback (most recent call last):
  File "/opt/bbot/bbot/scanner/manager.py", line 311, in catch
    ret = callback(*args, **kwargs)
  File "/opt/bbot/bbot/modules/base.py", line 122, in _if_not_errored
    return callback(*args, **kwargs)
  File "/opt/bbot/bbot/modules/output/web_report.py", line 70, in handle_event
    if event.type not in self.web_assets[host].keys():
KeyError: 'https://redacted/'

**Comment by liquidsec** [comment]
fixed in https://github.com/blacklanternsecurity/bbot/commit/c0d55feefe816b224ef28413709358861cd296d4
