### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'scope_distance' (wayback module)

### ISSUE THREAD

**Issue by liquidsec** [blacklanternsecurity/bbot#322]
2023-03-04 02:49:48,575 [TRACE] bbot.scanner.manager [manager.py:320](http://manager.py:320/) Traceback (most recent call last):
  File "/opt/bbot/bbot/scanner/manager.py", line 313, in catch
    ret = callback(*args, **kwargs)
  File "/opt/bbot/bbot/modules/base.py", line 188, in _postcheck_and_run
    return callback(event)
  File "/opt/bbot/bbot/modules/wayback.py", line 28, in handle_event
    self.emit_event(result, event_type, event, abort_if=self.abort_if)
  File "/opt/bbot/bbot/modules/base.py", line 240, in emit_event
    if event.scope_distance > 0:
AttributeError: 'NoneType' object has no attribute 'scope_distance'

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/327
