### ISSUE TITLE
Bug in sslcert

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#366]
```python
2023-03-13 12:45:37,450 [ERROR] bbot.scanner.manager [manager.py:317](http://manager.py:317/) Error in sslcert.visit_host(): module 'lib' has no attribute 'SSL_CTX_set_ecdh_auto'
2023-03-13 12:45:37,450 [TRACE] bbot.scanner.manager [manager.py:318](http://manager.py:318/) Traceback (most recent call last):
  File "/home/liquid/.local/lib/python3.10/site-packages/bbot/scanner/manager.py", line 311, in catch
    ret = callback(*args, **kwargs)
  File "/home/liquid/.local/lib/python3.10/site-packages/bbot/modules/sslcert.py", line 113, in visit_host
    context = SSL.Context(PROTOCOL_TLSv1)
  File "/home/liquid/.local/lib/python3.10/site-packages/OpenSSL/SSL.py", line 674, in __init__
AttributeError: module 'lib' has no attribute 'SSL_CTX_set_ecdh_auto'

2023-03-13 12:45:37,451 [ERROR] bbot.scanner.manager [manager.py:317](http://manager.py:317/) Error in sslcert.handle_event(): cannot unpack non-iterable NoneType object
2023-03-13 12:45:37,451 [TRACE] bbot.scanner.manager [manager.py:318](http://manager.py:318/) Traceback (most recent call last):
  File "/home/liquid/.local/lib/python3.10/site-packages/bbot/scanner/manager.py", line 311, in catch
    ret = callback(*args, **kwargs)
  File "/home/liquid/.local/lib/python3.10/site-packages/bbot/modules/base.py", line 223, in _postcheck_and_run
    return callback(event)
  File "/home/liquid/.local/lib/python3.10/site-packages/bbot/modules/sslcert.py", line 74, in handle_event
    dns_names, emails = future.result()
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/369
