### ISSUE TITLE
telerik canceled future bug

### ISSUE THREAD

**Issue by liquidsec** [blacklanternsecurity/bbot#382]
023-03-15 23:39:54,424 [ERROR] bbot.scanner.manager manager.py:318 Error in telerik.handle_event(): 
2023-03-15 23:39:54,612 [TRACE] bbot.scanner.manager manager.py:319 Traceback (most recent call last):
  File "/home-/bbot/bbot/scanner/manager.py", line 312, in catch
    ret = callback(*args, **kwargs)
  File "/home/-/bbot/bbot/modules/base.py", line 223, in _postcheck_and_run
    return callback(event)
  File "/home/-/bbot/bbot/modules/telerik.py", line 225, in handle_event
    result = future.result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 436, in result
    raise CancelledError()
concurrent.futures._base.CancelledError

**Comment by liquidsec** [comment]
fixed in https://github.com/blacklanternsecurity/bbot/pull/387
