### ISSUE TITLE
Bug in sslcert

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#386]
```python
2023-03-15 22:19:10,142 [TRACE] bbot.scanner.manager manager.py:319 Traceback (most recent call last):
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.10/site-packages/bbot/scanner/manager.py", line 312, in catch
    ret = callback(*args, **kwargs)
  File "/home/user/.local/pipx/venvs/bbot/lib/python3.10/site-packages/bbot/modules/sslcert.py", line 114, in visit_host
    sock = socket.socket(socket_type, socket.SOCK_STREAM)
  File "/usr/lib/python3.10/socket.py", line 232, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol
```

**Comment by TheTechromancer** [comment]
This seems to happens on systems with IPv6 disabled at the kernel level (e.g. as a security measure).

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/405/commits/c119fc5eb4421efcfbc66840150c92a59daf4222
