### ISSUE TITLE
sslcert bug

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#434]
```python
2023-03-31 04:07:44,154 [ERROR] bbot.scanner.manager manager.py:327 Error in sslcert.visit_host(): cannot use string() on <cdata 'char *' NULL>
2023-03-31 04:07:44,155 [TRACE] bbot.scanner.manager manager.py:328 Traceback (most recent call last):
  File "/root/bbot/bbot/scanner/manager.py", line 321, in catch
    ret = callback(*args, **kwargs)
  File "/root/bbot/bbot/modules/sslcert.py", line 163, in visit_host
    dns_names = set(self.get_cert_sans(cert))
  File "/root/bbot/bbot/modules/sslcert.py", line 176, in get_cert_sans
    if "subjectAltName" in str(ext.get_short_name()):
  File "/root/.cache/pypoetry/virtualenvs/bbot-aKeTQkGo-py3.9/lib/python3.9/site-packages/OpenSSL/crypto.py", line 907, in get_short_name
    return _ffi.string(_lib.OBJ_nid2sn(nid))
RuntimeError: cannot use string() on <cdata 'char *' NULL>
```

**Comment by TheTechromancer** [comment]
Looks like an upstream bug in PyOpenSSL.
https://github.com/pyca/pyopenssl/issues/1207

**Comment by TheTechromancer** [comment]
Fixed by upgrading pyopenssl to latest version
