### ISSUE TITLE
Logging not initialized properly when importing via Python

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#457]
```bash
$ python3
Python 3.10.10 (main, Mar  5 2023, 22:26:53) [GCC 12.2.1 20230201] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bbot.core.helpers.wordcloud
[INFO] bbot: Loaded defaults from /home/bls/Downloads/code/bbot/bbot/defaults.yml
[INFO] bbot: Loaded config from /home/bls/.config/bbot/bbot.yml
[INFO] bbot: Loaded secrets from /home/bls/.config/bbot/secrets.yml
>>> m = bbot.core.helpers.wordcloud.DNSMutator()
>>> m.add_word('redirector')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bls/Downloads/code/bbot/bbot/core/helpers/wordcloud.py", line 275, in add_word
    log.hugesuccess(start)
AttributeError: 'Logger' object has no attribute 'hugesuccess'
```

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/458
