### ISSUE TITLE
input() EOFError

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#487]
Logging level toggle thread sometimes dies unexpectedly.
~~~python
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/root/bbot/bbot/cli.py", line 270, in keyboard_listen
    keyboard_input = input()
EOFError
~~~

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/489
