### ISSUE TITLE
Filename is too long

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#491]
~~~
[ERRR] bbot: Encountered unknown error: Traceback (most recent call last):
  File "/root/bbot/bbot/cli.py", line 46, in main
    check_cli_args()
  File "/root/bbot/bbot/core/configurator/__init__.py", line 45, in check_cli_args
    if not Path(c).is_file():
  File "/usr/lib/python3.9/pathlib.py", line 1439, in is_file
    return S_ISREG(self.stat().st_mode)
  File "/usr/lib/python3.9/pathlib.py", line 1221, in stat
    return self._accessor.stat(self)
~~~

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/489
