### ISSUE TITLE
str' object has no attribute 'get' (crobat modules)

### ISSUE THREAD

**Issue by liquidsec** [blacklanternsecurity/bbot#522]
2023-05-09 17:03:28,500 [TRACE] bbot.modules.certspotter base.py:682 Traceback (most recent call last):
  File "/root/bbot/bbot/modules/crobat.py", line 125, in query
    results = list(parse_fn(request_fn(query), query))
  File "/root/bbot/bbot/modules/certspotter.py", line 20, in parse_results
    for dns_name in r.get("dns_names", []):
AttributeError: 'str' object has no attribute 'get'

**Comment by TheTechromancer** [comment]
@liquidsec  I'm having trouble reproducing this. What was the target domain?

**Comment by TheTechromancer** [comment]
Closing
