### ISSUE TITLE
SSLCert AttributeError: 'NoneType' object has no attribute '_get_extra_info'

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#542]
```
[ERRR] Error in sslcert.handle_event: /usr/local/lib/python3.11/asyncio/sslproto.py:91:get_extra_info(): 'NoneType' object has no attribute '_get_extra_info'
```
```
bbot.scanner logger.py:90 Traceback (most recent call last):
  File "/root/bbot/bbot/scanner/scanner.py", line 683, in acatch
    yield
  File "/root/bbot/bbot/modules/base.py", line 346, in _worker
    await self.handle_event(event)
  File "/root/bbot/bbot/modules/sslcert.py", line 72, in handle_event
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 605, in _wait_for_one
    return f.result()  # May raise f.exception().
           ^^^^^^^^^^
  File "/root/bbot/bbot/modules/sslcert.py", line 143, in visit_host
    ssl_object = transport.get_extra_info("ssl_object")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/sslproto.py", line 91, in get_extra_info
    return self._ssl_protocol._get_extra_info(name, default)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_get_extra_info'
```

**Comment by TheTechromancer** [comment]
Fixed in 7d26b8762d16ad42e232a95ecefab6daf979aa8c
