### ISSUE TITLE
Scan Fails to Finish

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#553]
There are no modules running and no events in the queue, but the scan continues to run. We need a debug status message that shows the value of every variable being used to calculate whether the scan is finished.

```
[INFO] async-test-3: Events produced so far: IP_ADDRESS: 56745, URL_UNVERIFIED: 18860, DNS_NAME: 14390, DNS_NAME_UNRESOLVED: 4688, URL: 4060, HTTP_RESPONSE: 4060, OPEN_TCP_PORT: 3673, ASN: 619, EMAIL_ADDRESS: 311, FINDING: 189, PROTOCOL: 33, STORAGE_BUCKET: 29
[VERB] async-test-3: Modules errored: 10 (anubisdb, azure_tenant, certspotter, columbus, crt, dnsdumpster, hackertarget, leakix, otx, rapiddns)
[INFO] async-test-3: No events in queue
```

On cancelling, there are multiprocessing errors:
```
Process SpawnProcess-2:
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/concurrent/futures/process.py", line 240, in _process_worker
    call_item = call_queue.get(block=True)
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 102, in get
    with self._rlock:
  File "/usr/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
Traceback (most recent call last):
KeyboardInterrupt
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/concurrent/futures/process.py", line 240, in _process_worker
    call_item = call_queue.get(block=True)
  File "/usr/lib/python3.10/multiprocessing/queues.py", line 103, in get
    res = self._recv_bytes()
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
```

**Comment by TheTechromancer** [comment]
Debug machinery has been added. However I haven't been able to reproduce this issue since then. We can re-open if it reappears.
