### ISSUE TITLE
Telerik Futures Error

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#558]
```
RuntimeError: Task <Task pending name='Task-19310' coro=<telerik.test_detector() running at /home/user/in3r9qut9b/.local/lib/python3.9/site-packages/bbot/modules/telerik.py:284> cb=[as_completed.<locals>._on_completion() at /usr/lib/python3.9/asyncio/tasks.py:601]> got Future <Future pending> attached to a different loop
Task exception was never retrieved
future: <Task finished name='Task-19311' coro=<telerik.test_detector() done, defined at /home/user/in3r9qut9b/.local/lib/python3.9/site-packages/bbot/modules/telerik.py:278> exception=RuntimeError("Task <Task pending name='Task-19311' coro=<telerik.test_detector() running at /home/user/in3r9qut9b/.local/lib/python3.9/site-packages/bbot/modules/telerik.py:284> cb=[as_completed.<locals>._on_completion() at /usr/lib/python3.9/asyncio/tasks.py:601]> got Future <Future pending> attached to a different loop")>
Traceback (most recent call last):
  File "/home/user/in3r9qut9b/.local/lib/python3.9/site-packages/bbot/modules/telerik.py", line 284, in test_detector
    result = await self.helpers.request(url, timeout=self.timeout)
  File "/home/user/in3r9qut9b/.local/lib/python3.9/site-packages/bbot/core/helpers/web.py", line 103, in request
    async with self.web_rate_limiter:
  File "/home/user/in3r9qut9b/.local/lib/python3.9/site-packages/bbot/core/helpers/ratelimiter.py", line 19, in __aenter__
    async with self.lock:
  File "/usr/lib/python3.9/asyncio/locks.py", line 14, in __aenter__
    await self.acquire()
  File "/usr/lib/python3.9/asyncio/locks.py", line 120, in acquire
    await fut
```

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/commit/0e4bb5d97eac2c66ed3738a8c20e4009996eaea6
