### ISSUE TITLE
async branch - wayback port out of range

### ISSUE THREAD

**Issue by liquidsec** [blacklanternsecurity/bbot#567]
```
2023-06-25 20:54:13,165 [ERROR] bbot.scanner scanner.py:758 Error in wayback.handle_event: /usr/lib/python3.10/urllib/parse.py:180:port(): Port out of range 0-65535
2023-06-25 20:54:13,166 [TRACE] bbot.scanner scanner.py:759 Traceback (most recent call last):
  File "/opt/bbot/bbot/scanner/scanner.py", line 727, in acatch
    yield
  File "/opt/bbot/bbot/modules/base.py", line 350, in _worker
    await self.handle_event(event)
  File "/opt/bbot/bbot/modules/wayback.py", line 27, in handle_event
    for result, event_type in await self.query(query):
  File "/opt/bbot/bbot/modules/wayback.py", line 53, in query
    for parsed_url in self.helpers.collapse_urls(urls, threshold=self.garbage_threshold):
  File "/opt/bbot/bbot/core/helpers/url.py", line 122, in collapse_urls
    new_url = clean_url(url)
  File "/opt/bbot/bbot/core/helpers/url.py", line 76, in clean_url
    if (parsed.scheme == "http" and parsed.port == 80) or (parsed.scheme == "https" and parsed.port == 443):
  File "/usr/lib/python3.10/urllib/parse.py", line 180, in port
    raise ValueError("Port out of range 0-65535")
ValueError: Port out of range 0-65535
```

**Comment by TheTechromancer** [comment]
Fixed in 14e528d3a395c19f40bed737186c9c39765ae5f3
