### ISSUE TITLE
crt module json decode error

### ISSUE THREAD

**Issue by liquidsec** [blacklanternsecurity/bbot#568]
```
2023-06-25 20:54:00,268 [INFO] bbot.modules.crt base.py:631 Error retrieving results for *redacted*: Expecting value: line 1 column 1 (char 0)
2023-06-25 20:54:00,268 [TRACE] bbot.modules.crt base.py:668 Traceback (most recent call last):
  File "/opt/bbot/bbot/modules/crobat.py", line 126, in query
    results = list(parse_fn(await request_fn(query), query))
  File "/opt/bbot/bbot/modules/crt.py", line 23, in parse_results
    j = r.json()
  File "/home/user/.cache/pypoetry/virtualenvs/bbot-IFSyk-JB-py3.10/lib/python3.10/site-packages/httpx/_models.py", line 755, in json
    return jsonlib.loads(self.content.decode(encoding), **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0
```

**Comment by TheTechromancer** [comment]
crt.sh is fairly unreliable due to the heavy load on their site. This is most likely a 502. A more informative error message has been added in 66610a798873b8f3990009c6b3be00753e8c314b.
