### ISSUE TITLE
censys: Error with API: 404 (not_found): The requested URL was not found.

### ISSUE THREAD

**Issue by emptysec1** [blacklanternsecurity/bbot#583]
**Describe the bug**
[What happened?](censys: Error with API: 404 (not_found): The requested URL was not found.)

**Expected behavior**
censys web interface shows 6 hosts search results for blacklanternsecurity.com, 
there are no results from censys module in bbot output file.

**BBOT Command**
bbot  -f subdomain-enum  -t blacklanternsecurity.com

**OS, BBOT Installation Method + Version**
OS: Ubuntu, Installation method: pip, BBOT version: 1.0.5.1665
**BBOT Config**
default

**Logs**

===

[TRACE] bbot.modules.censys base.py:682 Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/bbot/modules/censys.py", line 49, in query
    for result in self.certificates.search(
  File "/usr/local/lib/python3.10/dist-packages/censys/search/v1/api.py", line 141, in search
    payload = self._post(self.search_path, data=data)
  File "/usr/local/lib/python3.10/dist-packages/censys/common/base.py", line 213, in _post
    return self._make_call(self._session.post, endpoint, args, data, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/censys/common/base.py", line 37, in _wrapper
    return _impl()
  File "/usr/local/lib/python3.10/dist-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/censys/common/base.py", line 35, in _impl
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/censys/common/base.py", line 194, in _make_call
    raise censys_exception(
censys.common.exceptions.CensysNotFoundException: 404 (not_found): The requested URL was not found.

**Comment by TheTechromancer** [comment]
Hmm it looks like they deprecated their v1 API. I'll look into this.

**Comment by TheTechromancer** [comment]
PR created: https://github.com/blacklanternsecurity/bbot/pull/584

**Comment by TheTechromancer** [comment]
Fix merged into dev.
