### ISSUE TITLE
Asset Inventory Bug

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#616]
```
Traceback (most recent call last):
  File "/root/bbot/bbot/scanner/scanner.py", line 730, in acatch
    yield
  File "/root/bbot/bbot/scanner/scanner.py", line 422, in report
    await mod.report()
  File "/root/bbot/bbot/modules/output/asset_inventory.py", line 97, in report
    _, domain = self.helpers.split_domain(host)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/bbot/bbot/core/helpers/misc.py", line 196, in split_domain
    split = hostname.split(".")
```

**Comment by TheTechromancer** [comment]
Fixed in 8f06dfd05ebe065937ca05badc5794f60600261c
