### ISSUE TITLE
DNS Connection Lost Error

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#622]
```
[DNS_NAME]              blueorigin.com  TARGET  (a-record, distance-0, domain, in-scope, mx-record, ns-record, resolved, soa-record, target, txt-record)
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
pipe closed by peer or os.write(pipe, data) raised exception.
[ERRR] Error in handle_event(DNS_NAME("blueorigin.com", module=TARGET, tags={'in-scope', 'txt-record', 'ns-record', 'resolved', 'soa-record', 'distance-0', 'target', 'mx-record', 'a-record', 'domain'})): /usr/lib/python3.11/asyncio/streams.py:167:_drain_helper(): Connect
ion lost

Future exception was never retrieved
future: <Future finished exception=BrokenPipeError()>
Traceback (most recent call last):
  File "/root/bbot/bbot/core/helpers/command.py", line 67, in run_live
    await input_task
  File "/root/bbot/bbot/core/helpers/command.py", line 115, in _write_stdin
    await proc.stdin.drain()
  File "/usr/lib/python3.11/asyncio/streams.py", line 378, in drain
    await self._protocol._drain_helper()
  File "/usr/lib/python3.11/asyncio/streams.py", line 173, in _drain_helper
    await waiter
BrokenPipeError
[DNS_NAME]              svn-collab.blueorigin.com       rapiddns        (a-record, distance-0, in-scope, resolved, subdomain)
[DNS_NAME]              gitlab-aws-jwks-integration.blueorigin.com      rapiddns        (a-record, cloud-aws, cname-record, distance-0, in-scope, resolved, subdomain)
Future exception was never retrieved
future: <Future finished exception=BrokenPipeError()>
Traceback (most recent call last):
  File "/root/bbot/bbot/core/helpers/command.py", line 67, in run_live
    await input_task
  File "/root/bbot/bbot/core/helpers/command.py", line 115, in _write_stdin
    await proc.stdin.drain()
  File "/usr/lib/python3.11/asyncio/streams.py", line 378, in drain
    await self._protocol._drain_helper()
  File "/usr/lib/python3.11/asyncio/streams.py", line 173, in _drain_helper
    await waiter
BrokenPipeError
```

**Comment by TheTechromancer** [comment]
This was a subprocess bug. Fixed in https://github.com/blacklanternsecurity/bbot/pull/607/commits/7d21cd18d41cb3fd244825f1b9a8a35fcea5a50e.
