### ISSUE TITLE
Paramminer unhandled error in finish()

### ISSUE THREAD

**Issue by liquidsec** [blacklanternsecurity/bbot#642]
2023-07-30 22:19:59,942 [TRACE] bbot.scanner scanner.py:782 Traceback (most recent call last):
  File "/home/user/bbot/bbot/scanner/scanner.py", line 730, in acatch
    yield
  File "/home/user/bbot/bbot/modules/base.py", line 350, in _worker
    await self.finish()
  File "/home/user/bbot/bbot/modules/paramminer_headers.py", line 236, in finish
    results = await self.do_mining(untested_matches, url, batch_size, compare_helper)
  File "/home/user/bbot/bbot/modules/paramminer_headers.py", line 104, in do_mining
    async for result, reasons, reflection in self.binary_search(compare_helper, url, group):
  File "/home/user/bbot/bbot/modules/paramminer_headers.py", line 205, in binary_search
    match, reasons, reflection, subject_response = await self.check_batch(compare_helper, url, group_slice)
  File "/home/user/bbot/bbot/modules/paramminer_getparams.py", line 31, in check_batch
    return await compare_helper.compare(
  File "/home/user/bbot/bbot/core/helpers/diff.py", line 137, in compare
    await self._baseline()
  File "/home/user/bbot/bbot/core/helpers/diff.py", line 55, in _baseline
    raise HttpCompareError("Can't get baseline from source URL")
bbot.core.errors.HttpCompareError: Can't get baseline from source URL

**Comment by liquidsec** [comment]
should have been fixed with 
https://github.com/blacklanternsecurity/bbot/commit/170ddc49b55e746edcb7e3d4823b4a46e0eee226

**Comment by liquidsec** [comment]
closing unless seen again
