### ISSUE TITLE
Unhandled Error in handle_batch() - Separator is not found, and chunk exceed the limit

### ISSUE THREAD

**Issue by liquidsec** [blacklanternsecurity/bbot#645]
2023-07-31 03:06:41,874 [ERROR] bbot.scanner scanner.py:781 Error in handle_batch(): /usr/lib/python3.10/asyncio/streams.py:533:readline(): Separator is not found, and chunk exceed the limit
2023-07-31 03:06:41,874 [TRACE] bbot.scanner scanner.py:782 Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/streams.py", line 524, in readline
    line = await self.readuntil(sep)
  File "/usr/lib/python3.10/asyncio/streams.py", line 602, in readuntil
    raise exceptions.LimitOverrunError(
asyncio.exceptions.LimitOverrunError: Separator is not found, and chunk exceed the limit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/bbot/bbot/scanner/scanner.py", line 730, in acatch
    yield
  File "/opt/bbot/bbot/modules/base.py", line 224, in _handle_batch
    await self.handle_batch(*events)
  File "/opt/bbot/bbot/modules/httpx.py", line 110, in handle_batch
    async for line in self.helpers.run_live(command, input=list(stdin), stderr=subprocess.DEVNULL):
  File "/opt/bbot/bbot/core/helpers/command.py", line 56, in run_live
    line = await proc.stdout.readline()
  File "/usr/lib/python3.10/asyncio/streams.py", line 533, in readline
    raise ValueError(e.args[0])
ValueError: Separator is not found, and chunk exceed the limit

**Comment by liquidsec** [comment]
defcon branch

**Comment by TheTechromancer** [comment]
o no

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/637/commits/b80fd2b239dad79f806a0a72270afe01209daa00
