### ISSUE TITLE
URL Manipulation Bug

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#672]
```
2023-08-17 13:08:49,148 [ERROR] bbot.scanner scanner.py:781 Error in url_manipulation.handle_event(URL("https://m.locator.discounttire.com/", module=httpx, tags={'distance-0', 'ip-65-9-149-116', 'in-scope', 'dir', 'status-301', 'http-title-301-moved-permanently'})): /root/bbot_dev/bbot/core/helpers/diff.py:50:_baseline(): Can't get baseline from source URL: https://m.locator.discounttire.com/:None / https://m.locator.discounttire.com/?vr1lod=2ub4gy:None
2023-08-17 13:08:49,149 [TRACE] bbot.scanner scanner.py:782 Traceback (most recent call last):
  File "/root/bbot_dev/bbot/scanner/scanner.py", line 730, in acatch
    yield
  File "/root/bbot_dev/bbot/modules/base.py", line 363, in _worker
    await self.handle_event(event)
  File "/root/bbot_dev/bbot/modules/url_manipulation.py", line 50, in handle_event
    if await compare_helper.canary_check(event.data, mode="getparam") == False: 
  File "/root/bbot_dev/bbot/core/helpers/diff.py", line 202, in canary_check
    await self._baseline()
  File "/root/bbot_dev/bbot/core/helpers/diff.py", line 50, in _baseline
    raise HttpCompareError(
bbot.core.errors.HttpCompareError: Can't get baseline from source URL: https://m.locator.evilcorp.com/:None / https://m.locator.evilcorp.com/?vr1lod=2ub4gy:None
```

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/674
