### ISSUE TITLE
Agent: Unhandled Error on Websocket Timeout

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#760]
```
[ERRR] Encountered unknown error: Traceback (most recent call last):
  File "/home/bls/Downloads/code/bbot/bbot/cli.py", line 99, in _main
    await agent.start()
  File "/home/bls/Downloads/code/bbot/bbot/agent/agent.py", line 61, in start
    ws = await self.ws(rebuild=rebuild)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bls/Downloads/code/bbot/bbot/agent/agent.py", line 54, in ws
    self._ws = await websockets.connect(url, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bls/.cache/pypoetry/virtualenvs/bbot-yxGMlPK5-py3.11/lib/python3.11/site-packages/websockets/legacy/client.py", line 655, in __await_impl_timeout__
    return await self.__await_impl__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bls/.cache/pypoetry/virtualenvs/bbot-yxGMlPK5-py3.11/lib/python3.11/site-packages/websockets/legacy/client.py", line 659, in __await_impl__
    _transport, _protocol = await self._create_connection()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 634, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 674, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 8080)
```

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/761.
