### ISSUE TITLE
Wayback Error

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#762]
```
[ERRR] Error in wayback.handle_event(DNS_NAME("up.com", module=TARGET, tags={'distance-0', 'a-record', 'domain', 'resolved', 'mx-record', 'soa-record', 'txt-record', 'in-scope', 'ns-record', 'target'})): /home/bls/Downloads/code/bbot/bbot/core/helpers/validators.py:21:validate_wrapper(): Validation failed for ('up,nm78.com',), {}: Invalid hostname: "up,nm78.com"
[TRCE] Traceback (most recent call last):
  File "/home/bls/Downloads/code/bbot/bbot/core/helpers/validators.py", line 31, in validate_wrapper
    return func(*args)
           ^^^^^^^^^^^
  File "/home/bls/Downloads/code/bbot/bbot/core/helpers/validators.py", line 126, in validate_host
    raise ValidationError(f'Invalid hostname: "{host}"')
bbot.core.errors.ValidationError: Invalid hostname: "up,nm78.com"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bls/Downloads/code/bbot/bbot/scanner/scanner.py", line 1054, in _acatch
    yield
  File "/home/bls/Downloads/code/bbot/bbot/modules/base.py", line 597, in _worker
    await self.handle_event(event)
  File "/home/bls/Downloads/code/bbot/bbot/modules/wayback.py", line 27, in handle_event
    for result, event_type in await self.query(query):
                              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bls/Downloads/code/bbot/bbot/modules/wayback.py", line 53, in query
    for parsed_url in self.helpers.validators.collapse_urls(urls, threshold=self.garbage_threshold):
  File "/home/bls/Downloads/code/bbot/bbot/core/helpers/validators.py", line 226, in collapse_urls
    new_url = clean_url(url)
              ^^^^^^^^^^^^^^
  File "/home/bls/Downloads/code/bbot/bbot/core/helpers/validators.py", line 189, in clean_url
    hostname = validate_host(parsed.hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bls/Downloads/code/bbot/bbot/core/helpers/validators.py", line 33, in validate_wrapper
    raise ValueError(f"Validation failed for {args}, {kwargs}: {e}")
ValueError: Validation failed for ('up,nm78.com',), {}: Invalid hostname: "up,nm78.com"
```

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/764.
