### ISSUE TITLE
Tests Failing After PydanticV2 Update

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#817]
```
TRACE    bbot.core.event:logger.py:83 Traceback (most recent call last):
  File "/home/user/Downloads/code/bbot/bbot/core/event/base.py", line 184, in __init__
    self.data = self._sanitize_data(data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/Downloads/code/bbot/bbot/core/event/base.py", line 505, in _sanitize_data
    data = self._data_validator(**data).dict()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.cache/pypoetry/virtualenvs/bbot-yxGMlPK5-py3.11/lib/python3.11/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for _data_validator
banner
  Field required [type=missing, input_value={'host': 'api.publicAPIs....443, 'protocol': 'HTTP'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing
```

Upstream issue opened with Pydantic: https://github.com/pydantic/pydantic/issues/8006.

**Comment by TheTechromancer** [comment]
Resolved.
