### ISSUE TITLE
Fail to run after update 1.1.2

### ISSUE THREAD

**Issue by obreinx** [blacklanternsecurity/bbot#819]
After updating bbot , i am facing this output after using the following command `bbot -t domains.txt -f subdomain-enum -om subdomains -o subs/ -n company`
----------------+--------------------+
[WARN] This is a (safe) active scan. Non-intrusive connections will be made to target
[WARN] You have enabled the following slow modules: massdns. Scan may take a while
[INFO] Scan with 43 modules seeded with 1 targets
[ERRR] Encountered unknown error: Traceback (most recent call last):
  File "/root/.local/pipx/venvs/bbot/lib/python3.11/site-packages/bbot/cli.py", line 302, in _main
    await scanner._prep()
  File "/root/.local/pipx/venvs/bbot/lib/python3.11/site-packages/bbot/scanner/scanner.py", line 286, in _prep
    await self.load_modules()
  File "/root/.local/pipx/venvs/bbot/lib/python3.11/site-packages/bbot/scanner/scanner.py", line 516, in load_modules
    loaded_modules, failed = self._load_modules(modules)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/pipx/venvs/bbot/lib/python3.11/site-packages/bbot/scanner/scanner.py", line 1013, in _load_modules
    for module_name, module_class in module_loader.load_modules(modules).items():
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/pipx/venvs/bbot/lib/python3.11/site-packages/bbot/core/helpers/modules.py", line 252, in load_modules
    module = self.load_module(module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/pipx/venvs/bbot/lib/python3.11/site-packages/bbot/core/helpers/modules.py", line 276, in load_module
    module_variables = importlib.import_module(import_path, "bbot")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/.local/pipx/venvs/bbot/lib/python3.11/site-packages/bbot/modules/sslcert.py", line 2, in <module>
    from OpenSSL import crypto
ModuleNotFoundError: No module named 'OpenSSL'

┌──(root㉿UnrealSMB)-[/home/kali]
└─# /usr/lib/python3.11/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 5 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by TheTechromancer** [comment]
Thanks for opening an issue. This looks like it might be a problem with the python environment; specifically with the openssl package.

Can you try reinstalling bbot with pipx? If that doesn't work, you could try docker:

```bash
docker run -it blacklanternsecurity/bbot
```

Let me know if that works.

**Comment by obreinx** [comment]
i tried uninstalling by using
'pipx uninstall bbot'
then 
'pipx install bbot'
still the same error
tried to add some modules like -m badsecrets 
the error changed from OpenSSL to badsecrets

**Comment by TheTechromancer** [comment]
I tried with your version of python + pipx and I can't reproduce the bug.

It seems like you either have a corrupt python environment or a conflicting bbot installation somewhere else on your system. In these cases I highly recommend using docker. We can't assist with troubleshooting your local python setup.

**Comment by TheTechromancer** [comment]
Closing due to inactivity
