### ISSUE TITLE
Tests Fail with "Can't combine arc data with line data"

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#844]
This error has been happening pretty consistently after github downgraded their action runners.

```
2023-11-13T16:14:27.5994093Z -------------------------------- live log call ---------------------------------
2023-11-13T16:14:27.5994806Z INFO     bbot.test.zoomeye:base.py:116 Finished zoomeye module test
2023-11-13T16:14:28.4212791Z 
2023-11-13T16:14:28.4213549Z ------------------------------ live log teardown -------------------------------
2023-11-13T16:14:28.4214781Z DEBUG    asyncio:base_events.py:687 Close <_UnixSelectorEventLoop running=False closed=False debug=True>
2023-11-13T16:14:28.4216518Z DEBUG    asyncio:selector_events.py:64 Using selector: EpollSelector
2023-11-13T16:14:28.8409960Z PASSED                                                                   [100%]
2023-11-13T16:14:28.8410611Z INTERNALERROR> Traceback (most recent call last):
2023-11-13T16:14:28.8412121Z INTERNALERROR>   File "/home/runner/.cache/pypoetry/virtualenvs/bbot-pd-UZ8Fz-py3.12/lib/python3.12/site-packages/_pytest/main.py", line 271, in wrap_session
2023-11-13T16:14:28.8413415Z INTERNALERROR>     session.exitstatus = doit(config, session) or 0
2023-11-13T16:14:28.8414085Z INTERNALERROR>                          ^^^^^^^^^^^^^^^^^^^^^
2023-11-13T16:14:28.8415406Z INTERNALERROR>   File "/home/runner/.cache/pypoetry/virtualenvs/bbot-pd-UZ8Fz-py3.12/lib/python3.12/site-packages/_pytest/main.py", line 325, in _main
2023-11-13T16:14:28.8416833Z INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
2023-11-13T16:14:28.8418241Z INTERNALERROR>   File "/home/runner/.cache/pypoetry/virtualenvs/bbot-pd-UZ8Fz-py3.12/lib/python3.12/site-packages/pluggy/_hooks.py", line 493, in __call__
2023-11-13T16:14:28.8419606Z INTERNALERROR>     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
2023-11-13T16:14:28.8420438Z INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-13T16:14:28.8421832Z INTERNALERROR>   File "/home/runner/.cache/pypoetry/virtualenvs/bbot-pd-UZ8Fz-py3.12/lib/python3.12/site-packages/pluggy/_manager.py", line 115, in _hookexec
2023-11-13T16:14:28.8423200Z INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
2023-11-13T16:14:28.8424003Z INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-13T16:14:28.8425458Z INTERNALERROR>   File "/home/runner/.cache/pypoetry/virtualenvs/bbot-pd-UZ8Fz-py3.12/lib/python3.12/site-packages/pluggy/_callers.py", line 130, in _multicall
2023-11-13T16:14:28.8426633Z INTERNALERROR>     teardown[0].send(outcome)
2023-11-13T16:14:28.8428007Z INTERNALERROR>   File "/home/runner/.cache/pypoetry/virtualenvs/bbot-pd-UZ8Fz-py3.12/lib/python3.12/site-packages/pytest_cov/plugin.py", line 298, in pytest_runtestloop
2023-11-13T16:14:28.8429254Z INTERNALERROR>     self.cov_controller.finish()
2023-11-13T16:14:28.8430655Z INTERNALERROR>   File "/home/runner/.cache/pypoetry/virtualenvs/bbot-pd-UZ8Fz-py3.12/lib/python3.12/site-packages/pytest_cov/engine.py", line 44, in ensure_topdir_wrapper
2023-11-13T16:14:28.8431918Z INTERNALERROR>     return meth(self, *args, **kwargs)
2023-11-13T16:14:28.8432481Z INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-13T16:14:28.8433781Z INTERNALERROR>   File "/home/runner/.cache/pypoetry/virtualenvs/bbot-pd-UZ8Fz-py3.12/lib/python3.12/site-packages/pytest_cov/engine.py", line 254, in finish
2023-11-13T16:14:28.8434917Z INTERNALERROR>     self.cov.combine()
2023-11-13T16:14:28.8436451Z INTERNALERROR>   File "/home/runner/.cache/pypoetry/virtualenvs/bbot-pd-UZ8Fz-py3.12/lib/python3.12/site-packages/coverage/control.py", line 832, in combine
2023-11-13T16:14:28.8437603Z INTERNALERROR>     combine_parallel_data(
2023-11-13T16:14:28.8438945Z INTERNALERROR>   File "/home/runner/.cache/pypoetry/virtualenvs/bbot-pd-UZ8Fz-py3.12/lib/python3.12/site-packages/coverage/data.py", line 171, in combine_parallel_data
2023-11-13T16:14:28.8440225Z INTERNALERROR>     data.update(new_data, aliases=aliases)
2023-11-13T16:14:28.8441558Z INTERNALERROR>   File "/home/runner/.cache/pypoetry/virtualenvs/bbot-pd-UZ8Fz-py3.12/lib/python3.12/site-packages/coverage/sqldata.py", line 658, in update
2023-11-13T16:14:28.8442902Z INTERNALERROR>     raise DataError("Can't combine arc data with line data")
2023-11-13T16:14:28.8443864Z INTERNALERROR> coverage.exceptions.DataError: Can't combine arc data with line data
2023-11-13T16:14:28.8444458Z 
2023-11-13T16:14:28.8444757Z =========== 183 passed, 4784 warnings, 1 rerun in 2075.73s (0:34:35) ===========
```

**Comment by TheTechromancer** [comment]
There is an upstream issue for this here:

https://github.com/pytest-dev/pytest-cov/issues/243

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/845.
