### ISSUE TITLE
Censys Parsing Bug

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#868]
```
2023-11-27 19:26:19,746 [ERROR] bbot.scanner scanner.py:1053 Error in censys.handle_event(DNS_NAME("evilcorp.com", module=azure_tenant, tags={'mx-record', 'a-record', 'azure-tenant', 'resolve
d', 'soa-record', 'in-scope', 'domain', 'ns-record', 'txt-record'})): /usr/lib/python3.10/json/decoder.py:355:raw_decode(): Expecting value: line 1 column 1 (char 0)
2023-11-27 19:26:19,746 [TRACE] bbot.scanner scanner.py:1054 Traceback (most recent call last): 
  File "/root/.local/pipx/venvs/bbot/lib/python3.10/site-packages/bbot/scanner/scanner.py", line 1036, in _acatch
    yield
  File "/root/.local/pipx/venvs/bbot/lib/python3.10/site-packages/bbot/modules/base.py", line 608, in _worker
    await self.handle_event(event)
  File "/root/.local/pipx/venvs/bbot/lib/python3.10/site-packages/bbot/modules/templates/subdomain_enum.py", line 31, in handle_event
    results = await self.query(query)
  File "/root/.local/pipx/venvs/bbot/lib/python3.10/site-packages/bbot/modules/censys.py", line 60, in query
    d = resp.json()
  File "/root/.local/pipx/venvs/bbot/lib/python3.10/site-packages/httpx/_models.py", line 761, in json
    return jsonlib.loads(self.content, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/991.
