### ISSUE TITLE
BlockingIOError: [Errno 11] write could not complete without blocking

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#928]
```python
2023-12-21 17:52:34,669 [ERROR] bbot.scanner scanner.py:1053 Error in human.handle_event(FINDING("{'host': 'cn.evilcorp.com', 'description': 'Cryptographic Product identi...", module=badsecrets, 
tags={'in-scope', 'cloud-azure'})): /root/bbot_dev/bbot/core/helpers/logger.py:52:log_to_stderr(): [Errno 11] write could not complete without blocking                                                    
2023-12-21 17:52:34,669 [TRACE] bbot.scanner scanner.py:1054 Traceback (most recent call last):                                                                                                            
  File "/root/bbot_dev/bbot/scanner/scanner.py", line 1036, in _acatch                                                                                                                                     
    yield                                                                                                                                                                                                  
  File "/root/bbot_dev/bbot/modules/base.py", line 608, in _worker                                                                                                                                         
    await self.handle_event(event)                                                                                                                                                                         
  File "/root/bbot_dev/bbot/modules/output/human.py", line 34, in handle_event                                                                                                                             
    log_to_stderr(event_str, level="HUGEINFO", logname=False)                                                                                                                                              
  File "/root/bbot_dev/bbot/core/helpers/logger.py", line 52, in log_to_stderr                                                                                                                             
    print(msg, file=sys.stderr)                                                                                                                                                                            
BlockingIOError: [Errno 11] write could not complete without blocking
```

**Comment by TheTechromancer** [comment]
@liquidsec according to @aconite33 this happens when bbot encounters a huuuuuuuge asp.net viewstate. It might be good to put a length limit on those.

EDIT: I noticed this also produces the same error inside the logger for extra-large chunks of data such as http responses.

**Comment by TheTechromancer** [comment]
This has been addressed in https://github.com/blacklanternsecurity/bbot/pull/955. If it resurfaces, we should consider reimplementing `logging.QueueHandler`.
