### ISSUE TITLE
NSEC Parsing Error

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#931]
```
2023-12-22 19:18:49,668 [WARNING] bbot.modules.nsec base.py:1300 Error getting NSEC record for \000.evilcorp.com: split_port() failed to parse "\000.evilcorp.com"
2023-12-22 19:18:49,668 [TRACE] bbot.modules.nsec base.py:1351 Traceback (most recent call last):
  File "/root/bbot_dev/bbot/modules/nsec.py", line 30, in get_nsec_record
    for result in await self.helpers.resolve(domain, type="NSEC"):
  File "/root/bbot_dev/bbot/core/helpers/dns.py", line 172, in resolve
    r = await self.resolve_raw(query, **kwargs)
  File "/root/bbot_dev/bbot/core/helpers/dns.py", line 233, in resolve_raw
    r, e = await self._resolve_hostname(query, rdtype=t, **kwargs)
  File "/root/bbot_dev/bbot/core/helpers/dns.py", line 280, in _resolve_hostname
    parent = self.parent_helper.parent_domain(query)
  File "/root/bbot_dev/bbot/core/helpers/misc.py", line 289, in parent_domain
    host, port = split_host_port(d)
  File "/root/bbot_dev/bbot/core/helpers/misc.py", line 231, in split_host_port
    raise ValueError(f'split_port() failed to parse "{d}"')
ValueError: split_port() failed to parse "\000.evilcorp.com"
```

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/935.
