### ISSUE TITLE
Interactsh Poll Error

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#932]
```
2023-12-22 20:46:26,936 [ERROR] bbot.scanner scanner.py:1053 Error in Interactsh._poll_loop(): /root/bbot_dev/bbot/core/helpers/interactsh.py:238:poll(): 'NoneType' object has no attribute 'json'
2023-12-22 20:46:26,937 [TRACE] bbot.scanner scanner.py:1054 Traceback (most recent call last):
  File "/root/bbot_dev/bbot/scanner/scanner.py", line 1036, in _acatch
    yield
  File "/root/bbot_dev/bbot/core/helpers/interactsh.py", line 265, in poll_loop
    return await self._poll_loop(callback)
  File "/root/bbot_dev/bbot/core/helpers/interactsh.py", line 274, in _poll_loop
    data_list = await self.poll()
  File "/root/bbot_dev/bbot/core/helpers/interactsh.py", line 238, in poll
    data_list = r.json().get("data", None)
AttributeError: 'NoneType' object has no attribute 'json'
```

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/939.
