### ISSUE TITLE
Badsecrets Process Pool Bug

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#933]
This happened to @aconite33 on one of his scans. You can message either @aconite33 or myself for the exact target that appeared to trigger this error.

```
2023-12-22 20:46:14,174 [WARNING] bbot.modules.badsecrets base.py:1300 Error processing HTTP_RESPONSE("{'url': 'https://www.evilcorp.com:443/login', 'timestamp': '2023...", module=httpx, tags={'endpoint', 'in-scope', 'status-200', 'http-title-invoice-ninja-free-open-source', 'login-page', 'ip-4-3-2-1', 'cloud-azure'}): A process in the process pool was terminated abruptly while the future was running or pending.
2023-12-22 20:46:14,175 [TRACE] bbot.modules.badsecrets base.py:1351 Traceback (most recent call last):
  File "/root/bbot_dev/bbot/modules/badsecrets.py", line 36, in handle_event
    r_list = await self.scan.run_in_executor_mp(
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

```
2023-12-22 21:01:34,550 [WARNING] bbot.modules.badsecrets base.py:1300 Error processing HTTP_RESPONSE("{'url': 'https://evilcorp.com:8443', 'timestamp': '2023-12-22T21:00:51....", module=httpx, tags={'ip-1-2-3-4', 'in-scope', 'http-title-bad-request', 'dir', 'status-400'}): A child process terminated abruptly, the process pool is not usable anymore
2023-12-22 21:01:34,551 [TRACE] bbot.modules.badsecrets base.py:1351 Traceback (most recent call last):
  File "/root/bbot_dev/bbot/modules/badsecrets.py", line 36, in handle_event
    r_list = await self.scan.run_in_executor_mp(
  File "/root/bbot_dev/bbot/scanner/scanner.py", line 825, in run_in_executor_mp
    return self._loop.run_in_executor(self.process_pool, callback, *args)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 818, in run_in_executor
    executor.submit(func, *args), loop=self)
  File "/usr/lib/python3.10/concurrent/futures/process.py", line 715, in submit
    raise BrokenProcessPool(self._broken)
concurrent.futures.process.BrokenProcessPool: A child process terminated abruptly, the process pool is not usable anymore
```

**Comment by liquidsec** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/955
