### ISSUE TITLE
Error in bypass403

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#934]
```
2023-12-22 20:55:02,648 [ERROR] bbot.scanner scanner.py:1053 Error in bypass403.handle_event(URL("http://evilcorp.com/", module=httpx, tags={'status-401', 'in-scope', 'ip-192-254-188-216', 'dir'})): /root/bbot_dev/bbot/core/helpers/diff.py:50:_baseline(): Can't get baseline from source URL: http://evilcorp.com/?tolqw1=1:None / http://evilcorp.com/?ouj158=xobwhi&cotdd7=1:None
2023-12-22 20:55:02,649 [TRACE] bbot.scanner scanner.py:1054 Traceback (most recent call last):
  File "/root/bbot_dev/bbot/scanner/scanner.py", line 1036, in _acatch
    yield
  File "/root/bbot_dev/bbot/modules/base.py", line 608, in _worker
    await self.handle_event(event)
  File "/root/bbot_dev/bbot/modules/bypass403.py", line 127, in handle_event
    results = await self.do_checks(compare_helper, event, collapse_threshold)
  File "/root/bbot_dev/bbot/modules/bypass403.py", line 93, in do_checks
    match, reasons, reflection, subject_response = await compare_helper.compare(
  File "/root/bbot_dev/bbot/core/helpers/diff.py", line 137, in compare
    await self._baseline()
  File "/root/bbot_dev/bbot/core/helpers/diff.py", line 50, in _baseline
    raise HttpCompareError(
bbot.core.errors.HttpCompareError: Can't get baseline from source URL: http://evilcorp.com/?tolqw1=1:None / http://evilcorp.com/?ouj158=xobwhi&cotdd7=1:None
```

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/936.
