### ISSUE TITLE
Error Parsing URL

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#944]
```
[CRIT] internal.excavate: ParseResult(scheme='', netloc='', path='1https://twitter.com/dakami/status/792783226850926593', params='', query='', fragment='')
```

```
2023-12-25 20:02:45,551 [ERROR] bbot.scanner scanner.py:1053 Error in excavate.handle_event(HTTP_RESPONSE("{'url': 'https://raw.githubusercontent.com:443/trietptm/Security-News/e46fe769bf...", module=httpx, tags={'ip-185-199-111-133', 'status-200', 'internal', 'cdn-github', 'extension-txt', 'endpoint', 'distance-1'})): /home/bls/Downloads/code/bbot/bbot/core/helpers/misc.py:231:split_host_port(): split_port() failed to parse ""
2023-12-25 20:02:45,551 [TRACE] bbot.scanner logger.py:83 Traceback (most recent call last):
  File "/home/bls/Downloads/code/bbot/bbot/scanner/scanner.py", line 1036, in _acatch
    yield
  File "/home/bls/Downloads/code/bbot/bbot/modules/base.py", line 612, in _worker
    await handle_event_task
  File "/home/bls/Downloads/code/bbot/bbot/modules/internal/excavate.py", line 374, in handle_event
    await self.search(
  File "/home/bls/Downloads/code/bbot/bbot/modules/internal/excavate.py", line 339, in search
    await e.search(source, event, **kwargs)
  File "/home/bls/Downloads/code/bbot/bbot/modules/internal/excavate.py", line 96, in search
    url_event = self.report(result, name, event, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bls/Downloads/code/bbot/bbot/modules/internal/excavate.py", line 149, in report
    host, port = self.excavate.helpers.split_host_port(parsed_uri.netloc)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bls/Downloads/code/bbot/bbot/core/helpers/misc.py", line 231, in split_host_port
    raise ValueError(f'split_port() failed to parse "{d}"')
ValueError: split_port() failed to parse ""
```

**Comment by TheTechromancer** [comment]
Fixed in https://github.com/blacklanternsecurity/bbot/pull/945.
