### ISSUE TITLE
Recursion Error on Far-Out Events

### ISSUE THREAD

**Issue by TheTechromancer** [blacklanternsecurity/bbot#953]
```
2023-12-31 15:43:52,476 [ERROR] bbot.scanner scanner.py:1053 Error in httpx.handle_batch(): /home/bls/Downloads/code/bbot/bbot/core/event/base.py:1296:is_event(): maximum recursion depth exceeded in comparison
2023-12-31 15:43:52,521 [TRACE] bbot.scanner logger.py:83 Traceback (most recent call last):
  File "/home/bls/Downloads/code/bbot/bbot/scanner/scanner.py", line 1036, in _acatch
    yield
  File "/home/bls/Downloads/code/bbot/bbot/modules/base.py", line 360, in _handle_batch
    await self.handle_batch(*events)
  File "/home/bls/Downloads/code/bbot/bbot/modules/httpx.py", line 158, in handle_batch
    self.emit_event(j, "HTTP_RESPONSE", url_event, tags=url_event.tags)
  File "/home/bls/Downloads/code/bbot/bbot/modules/base.py", line 435, in emit_event
    event = self.make_event(*args, **event_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bls/Downloads/code/bbot/bbot/modules/base.py", line 390, in make_event
    event = self.scan.make_event(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bls/Downloads/code/bbot/bbot/scanner/scanner.py", line 772, in make_event
    event = make_event(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bls/Downloads/code/bbot/bbot/core/event/base.py", line 1235, in make_event
    return event_class(
           ^^^^^^^^^^^^
  File "/home/bls/Downloads/code/bbot/bbot/core/event/base.py", line 961, in __init__
    super().__init__(*args, **kwargs)
  File "/home/bls/Downloads/code/bbot/bbot/core/event/base.py", line 858, in __init__
    super().__init__(*args, **kwargs)
  File "/home/bls/Downloads/code/bbot/bbot/core/event/base.py", line 193, in __init__
    self.source = source
    ^^^^^^^^^^^
  File "/home/bls/Downloads/code/bbot/bbot/core/event/base.py", line 402, in source
    self.scope_distance = new_scope_distance
    ^^^^^^^^^^^^^^^^^^^
  File "/home/bls/Downloads/code/bbot/bbot/core/event/base.py", line 373, in scope_distance
    self.source.scope_distance = scope_distance + 1
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bls/Downloads/code/bbot/bbot/core/event/base.py", line 373, in scope_distance
    self.source.scope_distance = scope_distance + 1
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bls/Downloads/code/bbot/bbot/core/event/base.py", line 373, in scope_distance
    self.source.scope_distance = scope_distance + 1
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 969 more times]
  File "/home/bls/Downloads/code/bbot/bbot/core/event/base.py", line 372, in scope_distance
    if source_scope_distance >= 0 and self != self.source:
                                      ^^^^^^^^^^^^^^^^^^^
  File "/home/bls/Downloads/code/bbot/bbot/core/event/base.py", line 694, in __eq__
    other = make_event(other, dummy=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bls/Downloads/code/bbot/bbot/core/event/base.py", line 1190, in make_event
    if is_event(data):
       ^^^^^^^^^^^^^^
  File "/home/bls/Downloads/code/bbot/bbot/core/event/base.py", line 1296, in is_event
    return BaseEvent in e.__class__.__mro__
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded in comparison
```

**Comment by TheTechromancer** [comment]
Not a realistic bug, closing.
